train_data = [
    # ----------- Cabinet Maintenance -----------

    # lock replacement
    ("Lock replacement secures cabinet doors and prevents unauthorized access.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Lock replacements ensure cabinet safety and improve door functionality.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Cabinet lock replacement restores cabinet security and prevents tampering.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Cabinet lock replacements maintain safety and prolong cabinet lifespan.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Replacing lock secures doors and ensures smooth operation.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Replacing locks strengthens cabinet security and prevents damage.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing cabinet lock fixes faulty latches and restores security.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Replacing cabinet locks improves functionality and prevents break-ins.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Replaced a lock secured cabinet doors and enhanced safety.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced a locks restored security and improved cabinet usage.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a cabinet lock repaired faulty latches and ensured safety.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Replaced a cabinet locks enhanced door security and prevented tampering.", 
     {"entities": [(0, 25, "SKILL")]}),

    # handle replacement
    ("Handle replacement improves cabinet usability and secures doors.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Handle replacements maintain cabinet functionality and prevent damage.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Cabinet handle replacement fixes loose handles and ensures smooth operation.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Cabinet handle replacements restore cabinet usability and improve safety.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Replacing handle secures doors and improves cabinet performance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing handles strengthens cabinet doors and enhances functionality.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing cabinet handle fixes faulty latches and improves operation.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Replacing cabinet handles restores functionality and prevents break-ins.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Replaced a handle repaired loose components and secured the cabinet.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced a handles restored door functionality and improved cabinet usage.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a cabinet handle corrected alignment and enhanced cabinet security.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Replaced a cabinet handles maintained door integrity and prevented damage.", 
     {"entities": [(0, 25, "SKILL")]}),

    # cabinet refacing
    ("Cabinet refacing updates the appearance and extends cabinet lifespan.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Cabinet refacings refresh cabinet surfaces and improve functionality.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Refacing cabinet enhances aesthetics and prolongs cabinet usage.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Refacing cabinets renews surfaces and strengthens overall cabinet structure.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Refacing of cabinet improves cabinet look and restores functionality.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Refacing of cabinets updates worn surfaces and prevents further damage.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Refaced a cabinet renewed surface and enhanced cabinet durability.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Refaced a cabinets restored worn surfaces and improved cabinet safety.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Refaced cabinet refreshed appearance and prolonged cabinet lifespan.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Refaced cabinets enhanced surface quality and restored cabinet aesthetics.", 
     {"entities": [(0, 15, "SKILL")]}),

    # cabinet repair (hinges)
    ("Hinge replacement ensures cabinet doors swing smoothly and safely.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Hinge replacements maintain door alignment and prevent wear over time.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Cabinet hinge replacement fixes loose hinges and restores door functionality.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Cabinet hinge replacements secure doors and improve cabinet durability.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Replacing hinge corrects door alignment and enhances cabinet performance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing hinges strengthens cabinet doors and ensures smooth operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing cabinet hinge fixes squeaky doors and restores proper movement.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Replacing cabinet hinges maintains door stability and prevents misalignment.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Replaced a hinge repaired faulty connections and ensured smooth swing.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced a hinges restored door function and improved cabinet usage.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a cabinet hinge fixed misaligned doors and enhanced durability.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Replaced a cabinet hinges corrected alignment and ensured proper operation.", 
     {"entities": [(0, 25, "SKILL")]}),

    # hinge replacement (general)
    ("Hinge replacement ensures smooth door operation and prevents damage.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Hinge replacements maintain proper door alignment and functionality.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Cabinet hinge replacement fixes loose doors and improves cabinet safety.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Cabinet hinge replacements secure doors and enhance cabinet durability.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Replacing hinge corrects misalignment and ensures smooth door operation.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing hinges strengthens doors and maintains cabinet functionality.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing cabinet hinge fixes squeaky doors and restores smooth movement.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Replacing cabinet hinges ensures door stability and prevents misalignment.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Replaced a hinge repaired faulty doors and restored proper swing.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced a hinges fixed misaligned doors and enhanced cabinet safety.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a cabinet hinge corrected loose doors and restored alignment.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Replaced a cabinet hinges repaired faulty doors and maintained cabinet durability.", 
     {"entities": [(0, 25, "SKILL")]}),
]
