train_data = [
    # ----------- Deep Cleaning -----------

    # tile scrubbing
    ("Tile scrubbing removes dirt and grime from bathroom floors.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Tile scrubbings ensure all tiles remain spotless and shiny.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Scrubbing tile eliminates stubborn stains and buildup.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Scrubbing tiles keeps floors clean and hygienic.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Scrubbing of tile maintains the longevity of bathroom surfaces.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Scrubbing of tiles ensures grout lines remain clean.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Scrubbed a tile removed all stains and soap scum effectively.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Scrubbed a tiles cleaned the floor thoroughly.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Scrubbed tile polished surfaces and removed grime.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Scrubbed tiles restored shine and cleanliness to the floors.", 
     {"entities": [(0, 13, "SKILL")]}),

    # steam cleaning
    ("Steam cleaning removes deep-seated dirt from carpets and upholstery.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Cleaning with steam sanitizes floors and furniture effectively.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Cleaning by steam disinfects surfaces without chemicals.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Steam cleaned a carpet removed stubborn stains easily.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Steam cleaned sofas sanitized them thoroughly.", 
     {"entities": [(0, 13, "SKILL")]}),

    # stain removal
    ("Stain removal eliminates tough spots from carpets and fabrics.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Stain removals are essential for keeping upholstery clean and fresh.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removing stain from the couch improves its appearance and hygiene.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removing stains from the carpet enhances overall cleanliness.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Removing of stain on the sofa prevents permanent marks.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Removing of stains from upholstery maintains fabric quality.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Removed a stain from the carpet using a professional cleaning method.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removed a stains from the sofa restored its original look.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removed stain from the dining chair quickly and effectively.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Removed stains from curtains enhanced the room's overall cleanliness.", 
     {"entities": [(0, 13, "SKILL")]}),

    # upholstery deep cleaning
    ("Upholstery deep cleaning removes dirt and allergens from sofas.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Upholstery deep cleanings help maintain furniture hygiene and appearance.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Deep cleaning upholstery restores the look and feel of old furniture.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Deep cleaning upholsteries removes stains and embedded dust effectively.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Deep cleaning of upholstery protects the fabric and extends its life.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Deep cleaning of upholsteries ensures the sofa remains fresh and clean.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Deep cleaned a upholstery restored its original softness and shine.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Deep cleaned a upholsteries sanitized the furniture thoroughly.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Deep cleaned upholstery removed stubborn stains and odors.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Deep cleaned upholsteries enhanced the comfort and appearance of the sofa.", 
     {"entities": [(0, 21, "SKILL")]}),

    # mattress sanitizing
    ("Mattress sanitizing removes dust mites and allergens effectively.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Mattress sanitizings are essential for maintaining healthy sleeping surfaces.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Sanitizing mattress prevents buildup of germs and bacteria.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Sanitizing mattresses improves hygiene and extends mattress lifespan.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Sanitizing of mattress ensures a clean and healthy sleeping environment.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Sanitizing of mattresses protects the bed from dust and microbes.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Sanitized a mattress removed dust and stains thoroughly.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Sanitized a mattresses ensured complete hygiene of the sleeping area.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Sanitized mattress eliminated allergens effectively.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Sanitized mattresses improved overall bed hygiene.", 
     {"entities": [(0, 18, "SKILL")]}),

    # vacuuming carpet
    ("Vacuuming carpet removes dust and debris efficiently from floors.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Vacuuming carpets helps maintain a clean and hygienic home.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Vacuuming of carpet ensures the carpet fibers remain fresh.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Vacuuming of carpets is essential for keeping dust under control.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Carpet vacuuming removes pet hair and small debris effectively.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Carpet vacuumings improve indoor air quality and hygiene.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Vacuumed a carpet removed all dust and small particles thoroughly.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Vacuumed a carpets helped in keeping the home clean and tidy.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Vacuumed carpet efficiently removed embedded dirt and debris.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Vacuumed carpets thoroughly cleaned the floor and improved hygiene.", 
     {"entities": [(0, 16, "SKILL")]}),
]
