train_data = [
    # ----------- Door Maintenance -----------

    # door alignment
    ("Door alignment ensures smooth door operation and prevents sticking.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Door alignments maintain proper door function and improve cabinet usage.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Aligning door corrects misalignment and enhances door performance.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Aligning doors maintains cabinet door alignment and ensures smooth operation.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Aligning of door fixes sagging doors and restores proper swing.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Aligning of doors corrects crooked doors and prevents wear over time.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Aligned a door fixed misaligned doors and restored smooth operation.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Aligned a doors repaired crooked doors and ensured proper alignment.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Aligned door corrected sagging doors and enhanced cabinet performance.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Aligned doors restored proper function and improved door stability.", 
     {"entities": [(0, 12, "SKILL")]}),

    # door repair
    ("Door repair fixes broken doors and restores proper function.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Door repairs maintain door integrity and prevent further damage.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Repairing door restores alignment and ensures smooth operation.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Repairing doors corrects misalignment and strengthens cabinet doors.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Repairing of door fixes squeaky hinges and restores proper swing.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing of doors corrects warped panels and enhances door durability.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repaired a door fixed broken panels and restored proper function.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Repaired a doors corrected misaligned hinges and strengthened cabinet doors.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Repaired door restored proper swing and fixed sagging panels.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Repaired doors fixed warped panels and ensured smooth operation.", 
     {"entities": [(0, 12, "SKILL")]}),

    # weather stripping installation
    ("Weather stripping installation prevents drafts and improves door insulation.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Weather stripping installations maintain proper sealing and enhance energy efficiency.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Installing weather stripping seals gaps around doors and reduces energy loss.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Installing weather strippings ensures tight sealing and prevents drafts.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Installing of weather stripping corrects leaks and improves door efficiency.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Installing of weather strippings strengthens door seals and enhances insulation.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Installed a weather stripping repaired gaps and improved door insulation.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Installed a weather strippings fixed leaks and ensured proper sealing.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Installed weather stripping corrected gaps and enhanced door energy efficiency.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Installed weather strippings reinforced door seals and reduced energy loss.", 
     {"entities": [(0, 29, "SKILL")]}),

    # roller repair
    ("Roller repair fixes stuck rollers and restores smooth sliding of doors.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Roller repairs maintain proper roller function and improve door movement.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Roller track repair restores proper track alignment and smooth sliding.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Roller track repairs prevent sticking and enhance door operation.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repairing roller ensures smooth movement and fixes door jams.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing rollers corrects worn rollers and restores proper sliding.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing roller track aligns tracks and ensures smooth door operation.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Repairing roller tracks fixes misaligned tracks and enhances sliding.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Repairing of roller replaces worn rollers and improves functionality.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Repairing of rollers restores smooth sliding and prevents door jams.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Repairing of roller track corrects misaligned tracks and enhances movement.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Repairing of roller tracks fixes worn tracks and restores door function.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Repaired a roller fixed stuck rollers and restored smooth sliding.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repaired a rollers replaced worn rollers and improved door operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired a roller track fixed misaligned tracks and restored sliding.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired a roller tracks aligned tracks and ensured smooth movement.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repaired roller corrected worn rollers and enhanced door function.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Repaired rollers replaced damaged rollers and improved sliding operation.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Repaired roller track fixed bent tracks and restored proper alignment.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repaired roller tracks corrected misaligned tracks and ensured smooth operation.", 
     {"entities": [(0, 20, "SKILL")]}),

    # scratch repair
    ("Scratch repair removes surface scratches and restores door finish.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Scratch repairs maintain door appearance and prevent further damage.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Repairing scratch corrects minor door marks and smooths surfaces.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing scratches removes dents and improves door aesthetics.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing of scratch fixes surface imperfections and restores finish.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repairing of scratches restores door surface and prevents further wear.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired a scratch removed visible marks and restored smooth surface.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired a scratches fixed surface imperfections and improved door finish.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repaired scratch corrected minor scratches and enhanced door appearance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repaired scratches restored door surface and removed dents.", 
     {"entities": [(0, 17, "SKILL")]}),

    # dent repair
    ("Dent repair fixes minor door dents and restores the smooth surface.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Dent repairs maintain door integrity and remove unsightly dents.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Repairing dent corrects small dents and improves door appearance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repairing dents removes surface dents and restores proper finish.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing of dent fixes door imperfections and smooths out dents.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing of dents restores door surface and removes small dents.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repaired a dent corrected minor dents and improved door finish.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repaired a dents removed dents and restored smooth door surface.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired dent fixed visible dents and enhanced overall door appearance.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Repaired dents restored door surface and eliminated minor dents.", 
     {"entities": [(0, 14, "SKILL")]}),

    # automatic door mechanism
    ("Automatic door mechanism ensures smooth operation of sliding doors.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Automatic door mechanisms enhance door functionality and user safety.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Installing automatic door mechanism improves entrance convenience and reliability.", 
     {"entities": [(0, 33, "SKILL")]}),
    ("Installing automatic door mechanisms upgrades doors with modern functionality.", 
     {"entities": [(0, 34, "SKILL")]}),
    ("Installing of automatic door mechanism provides efficient entry and exit.", 
     {"entities": [(0, 36, "SKILL")]}),
    ("Installing of automatic door mechanisms allows doors to operate smoothly.", 
     {"entities": [(0, 37, "SKILL")]}),
    ("Installed a automatic door mechanism enhanced door convenience and security.", 
     {"entities": [(0, 35, "SKILL")]}),
    ("Installed a automatic door mechanisms upgraded doors with automated functionality.", 
     {"entities": [(0, 36, "SKILL")]}),
    ("Installed automatic door mechanism improved entry system and overall door operation.", 
     {"entities": [(0, 34, "SKILL")]}),
    ("Installed automatic door mechanisms allowed smooth operation and increased safety of doors.", 
     {"entities": [(0, 35, "SKILL")]}),

    # hinge adjustment
    ("Hinge adjustment ensures proper door alignment and smooth operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Hinge adjustments correct misaligned doors and prevent further wear.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Adjusting hinge fixes minor misalignment and improves door performance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Adjusting hinges corrects alignment issues and ensures smooth door operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Adjusting of hinge restores proper door swing and prevents sticking.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Adjusting of hinges improves door movement and prevents squeaking.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Adjusted a hinge corrected door alignment and restored smooth operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Adjusted a hinges fixed door misalignment and improved performance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Adjusted hinge restored proper door swing and prevented sticking.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Adjusted hinges corrected alignment issues and enhanced door functionality.", 
     {"entities": [(0, 16, "SKILL")]}),
]
