training_data = [
    # ----------- Drain Unclogging -----------

    # Drain Cleaning
    ("Drain cleaning is essential to prevent clogs and backups.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Drain cleanings occur regularly in commercial properties.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Cleaning drain requires proper tools and careful handling.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Cleaning drains is often performed by professional plumbers.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Cleaning of drain takes priority after heavy rainfall.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Cleaning of drains is part of routine maintenance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("The plumber cleaned a drain in the basement yesterday.", 
     {"entities": [(12, 28, "SKILL")]}),
    ("He cleaned a drains quickly to restore proper flow.", 
     {"entities": [(3, 19, "SKILL")]}),
    ("Cleaned drain was maintained by the maintenance team.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("The team cleaned drains in multiple apartments yesterday.", 
     {"entities": [(9, 24, "SKILL")]}),

    # Drain Snaking
    ("Snaking drain requires proper tools and expertise.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Snaking drains is often handled by professional plumbers.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Snaking of drain was scheduled for the morning.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Snaking of drains is part of routine maintenance.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("The plumber snaked a drain to clear the blockage.", 
     {"entities": [(12, 27, "SKILL")]}),
    ("He snaked a drains quickly to restore proper flow.", 
     {"entities": [(3, 17, "SKILL")]}),
    ("Snaked drain was maintained by the maintenance team.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("The team snaked drains in multiple apartments yesterday.", 
     {"entities": [(9, 21, "SKILL")]}),
    ("Drain repair is sometimes necessary after heavy usage.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Routine drain repair prevents blockages in commercial buildings.", 
     {"entities": [(8, 21, "SKILL")]}),

    # Hydro Jetting
    ("Hydro jetting is used to clear tough drain blockages.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Hydro jetting prevents buildup in commercial plumbing systems.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Performing hydro jetting requires high-pressure equipment.", 
     {"entities": [(11, 25, "SKILL")]}),
    ("Executing hydro jetting is part of professional drain maintenance.", 
     {"entities": [(10, 23, "SKILL")]}),
    ("The plumber completed hydro jetting on the main sewer line.", 
     {"entities": [(22, 36, "SKILL")]}),
    ("He performed hydro jetting yesterday to unclog the drains.", 
     {"entities": [(13, 26, "SKILL")]}),

    # Clog Removal
    ("Clog removal is necessary to maintain proper drainage.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Removal of clog is performed frequently in commercial kitchens.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removal of clogs helps prevent plumbing emergencies.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Removing clog requires proper tools and careful handling.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removing clogs is often handled by professional plumbers.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removing of clog was part of the routine maintenance.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Removing of clogs requires high-pressure equipment.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("The plumber removed a clog from the kitchen sink.", 
     {"entities": [(12, 27, "SKILL")]}),
    ("He removed a clogs quickly to restore drainage.", 
     {"entities": [(3, 18, "SKILL")]}),
    ("Removed clog was maintained by the maintenance team.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("The team removed clogs in multiple apartments yesterday.", 
     {"entities": [(9, 21, "SKILL")]}),
]
