train_data = [
    # ----------- Electric Fan Maintenance -----------

    # motor cleaning
    ("Motor cleaning removes accumulated dust for optimal fan performance.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Cleaning motor ensures smooth operation and reduces noise.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Cleaning motors prevents overheating and prolongs fan life.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Cleaned motor restored proper airflow and reduced vibrations.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Cleaned motors removed dust and improved efficiency.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Cleaned a motor ensured smooth and silent operation.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Cleaned a motors prevented overheating and motor damage.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Cleaning of motor maintains optimal performance of the fan.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Cleaning of motors reduces wear and tear on fan components.", 
     {"entities": [(0, 17, "SKILL")]}),

    # motor lubrication
    ("Motor lubrication ensures smooth rotation and prevents wear.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Lubrication of motor reduces friction and prolongs motor life.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Lubrication of motors maintains efficient fan performance.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Lubricated motor restored smooth operation and minimized noise.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Lubricated motors improved rotation efficiency and reduced wear.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Lubricated a motor ensured quiet and smooth functioning.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Lubricated a motors prevented friction-related damage.", 
     {"entities": [(0, 18, "SKILL")]}),

    # blade replacement
    ("Blade replacement ensures optimal airflow from the electric fan.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Blade replacements prevent imbalanced rotation and fan noise.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing blade maintains smooth operation and consistent airflow.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing blades improves fan efficiency and reduces vibrations.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing of blade prevents wear and ensures long-lasting performance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing of blades maintains balance and optimal airflow.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a blade restored proper rotation and balanced airflow.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced a blades fixed wobbling and improved fan performance.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced blade ensured smooth operation and efficient airflow.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Replaced blades prevented imbalance and reduced fan noise.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacement of blade is necessary for optimal fan performance.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replacement of blades maintains balance and smooth airflow.", 
     {"entities": [(0, 22, "SKILL")]}),

    # oscillation mechanism repair
    ("Oscillation mechanism repair restores smooth side-to-side movement.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Oscillation mechanism repairs prevent jerky movements and imbalance.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repairing oscillation mechanism ensures consistent fan rotation.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repairing oscillation mechanisms maintains smooth oscillatory motion.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Repairing of oscillation mechanism fixes wobbling and uneven rotation.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Repairing of oscillation mechanisms prevents mechanical wear and tear.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Repaired a oscillation mechanism restored smooth fan movement.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Repaired a oscillation mechanisms fixed jerky motion and imbalance.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Repaired oscillation mechanism improved side-to-side operation.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repaired oscillation mechanisms restored proper oscillatory function.", 
     {"entities": [(0, 29, "SKILL")]}),

    # speed control repair
    ("Speed control repair ensures consistent fan speed and smooth operation.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Speed control repairs prevent sudden speed changes and uneven rotation.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Speed controller repair maintains proper voltage regulation for fans.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Speed controller repairs prevent malfunction and ensure smooth operation.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Repairing speed control maintains steady fan rotation and performance.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repairing speed controls ensures proper adjustment of fan speed.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Repairing speed controller prevents speed fluctuation and noise.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Repairing speed controllers maintains consistent airflow and performance.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Repairing of speed control fixes irregular speed issues effectively.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Repairing of speed controls restores proper fan speed adjustment.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Repairing of speed controller prevents motor damage due to overspeed.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Repairing of speed controllers ensures smooth and safe operation.", 
     {"entities": [(0, 33, "SKILL")]}),
    ("Repaired a speed control restored stable fan operation.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Repaired a speed controls fixed inconsistent speed issues.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Repaired a speed controller improved fan performance and consistency.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Repaired a speed controllers prevented motor damage and imbalance.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repaired speed control ensured proper speed regulation.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repaired speed controls maintained smooth and even rotation.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired speed controller fixed erratic fan speed efficiently.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repaired speed controllers restored consistent motor performance.", 
     {"entities": [(0, 24, "SKILL")]}),

    # bearing replacement
    ("Bearing replacement ensures smooth rotation and reduces fan noise.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Bearing replacements prevent wear and prolong motor life.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Replacing bearing maintains consistent fan operation and efficiency.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing bearings restores smooth airflow and reduces vibrations.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing of bearing prevents motor friction and imbalance.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replacing of bearings ensures proper rotation and fan stability.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Replaced a bearing restored smooth fan rotation and performance.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replaced a bearings fixed uneven rotation and reduced noise.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Replaced bearing improved fan stability and motor efficiency.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replaced bearings restored balanced rotation and smooth operation.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacement of bearing ensures smooth motor performance.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Replacement of bearings prevents imbalance and prolongs fan life.", 
     {"entities": [(0, 23, "SKILL")]}),
]
