train_data = [
    # ----------- Electrical Wiring and Rewiring -----------

    # wire installation
    ("Wire installation is essential for safe electrical wiring.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Wire installations require certified electricians for proper setup.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Installation of wire must follow electrical safety regulations.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Installation of wires ensures proper connectivity in circuits.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Installing of wire helps complete the circuit installation.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Installing of wires is included in all electrical maintenance tasks.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Installing wire requires careful measurement and routing.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Installing wires ensures proper connection between components.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Installed wire was inspected to confirm correct connections.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Installed wires improved the circuit performance in the building.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Installed a wire ensured continuity throughout the electrical system.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Installed a wires replaced faulty connections in the main panel.", 
     {"entities": [(0, 17, "SKILL")]}),

    # conduit installation
    ("Conduit installation ensures safe routing of electrical wiring.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Conduit installations are required in all new electrical setups.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Installation of conduit must follow electrical safety standards.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Installation of conduits ensures organized and safe wiring.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Installing of conduit helps protect wires from physical damage.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Installing of conduits is part of standard electrical installation tasks.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Installing conduit requires accurate measurement and placement.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Installing conduits ensures proper wiring layout in buildings.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Installed conduit was checked for proper alignment and security.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Installed conduits improved overall wiring safety in the facility.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Installed a conduit replaced the old, damaged conduit in the wall.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Installed a conduits ensured secure electrical connections throughout the building.", 
     {"entities": [(0, 21, "SKILL")]}),

    # electrical insulation
    ("Electrical insulation prevents short circuits and enhances safety.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Insulation of electrical wiring is essential for all wiring projects.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Insulation of electrical wirings ensures proper protection of circuits.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Insulating electrical wiring is part of routine electrical maintenance.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Insulating electrical wirings prevents electrical hazards in buildings.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Insulating of electrical wiring helps maintain circuit integrity.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Insulating of electrical wirings ensures safety and compliance.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Insulated a electrical wiring was checked for proper coverage.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Insulated a electrical wirings improved overall circuit safety.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Insulated electrical wiring prevents energy loss in the system.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Insulated electrical wirings were tested for proper functionality.", 
     {"entities": [(0, 28, "SKILL")]}),

    # circuit connection
    ("Circuit connection ensures proper flow of electricity in systems.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Circuit connections are inspected regularly to maintain electrical safety.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Connecting circuit requires careful handling to avoid short circuits.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Connecting circuits is part of standard electrical installation procedures.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Connecting of circuit ensures all components are properly linked.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Connecting of circuits improves safety and reduces the risk of faults.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Connection of circuit must follow safety and wiring standards.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Connection of circuits ensures proper network distribution in the panel.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Connected a circuit was tested for continuity and performance.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Connected a circuits improved overall electrical network reliability.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Connected circuit replaced the faulty connection in the system.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Connected circuits ensured proper electricity distribution throughout.", 
     {"entities": [(0, 18, "SKILL")]}),
]
