train_data = [
    # ----------- General Cleaning -----------

    # sweeping floor
    ("Sweeping floor keeps the room tidy and removes dirt from surfaces.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Sweeping floors removes dust and maintains cleanliness in the home.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Sweeping of floor ensures all corners are clean and dust-free.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Sweeping of floors eliminates debris and keeps surfaces spotless.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Floor sweeping maintains hygiene and removes scattered dirt.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Floor sweepings clean all areas thoroughly and improve appearance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Swept a floor removed dust and dirt, leaving it clean and tidy.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Swept a floors cleaned the living room and maintained hygiene.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Swept floor tidied all rooms and removed debris from corners.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Swept floors ensured cleanliness and maintained a neat environment.", 
     {"entities": [(0, 12, "SKILL")]}),

    # mopping floor
    ("Mopping floor removes dirt and maintains a clean home environment.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Mopping floors ensures all surfaces are spotless and hygienic.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Mopping of floors keeps the area tidy and free from stains.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Floor mopping effectively cleans and sanitizes all walking areas.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Floor moppings maintain hygiene and improve the appearance of rooms.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Mopped a floor removed dust and stains, leaving the room spotless.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Mopped a floors cleaned the entire kitchen and maintained hygiene.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Mopped floor ensured all areas were clean and free from grime.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Mopped floors tidied the hallway and removed sticky residues.", 
     {"entities": [(0, 12, "SKILL")]}),

    # surface wiping
    ("Surface wiping removes dust and grime from all furniture surfaces.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Surface wipings ensure all counters and tables remain spotless.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Wiping surface cleans the table thoroughly and maintains hygiene.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Wiping surfaces removes dust from shelves and cabinets.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Wiping of surface ensures cleanliness and prevents stains.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Wiping of surfaces sanitizes all areas and removes residues.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Wiped a surface removed sticky residues and dust from the table.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Wiped a surfaces cleaned the counters thoroughly.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Wiped surface ensured all surfaces were free of dust and dirt.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Wiped surfaces maintained hygiene and cleanliness in the office.", 
     {"entities": [(0, 14, "SKILL")]}),

    # vacuuming carpet
    ("Vacuuming carpet removes dirt and dust from all floor areas.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Vacuuming carpets ensures all rugs are clean and dust-free.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Vacuuming of carpet effectively removes pet hair and debris.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Vacuuming of carpets maintains cleanliness and hygiene in rooms.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Carpet vacuuming keeps all areas spotless and free from dust.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Carpet vacuumings remove dirt and maintain a tidy environment.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Vacuumed a carpet removed dust and debris from the living room.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Vacuumed a carpets cleaned all rugs thoroughly.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Vacuumed carpet ensured all areas were free from dust and dirt.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Vacuumed carpets maintained hygiene and cleanliness in the home.", 
     {"entities": [(0, 15, "SKILL")]}),

    # organizing
    ("Organizing the kitchen shelves makes it easier to find utensils.", 
     {"entities": [(0, 10, "SKILL")]}),
    ("Organizing of the living room items improves room aesthetics.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Organizing closets ensures all clothes are in proper order.", 
     {"entities": [(0, 10, "SKILL")]}),
    ("Organizing of office supplies reduces clutter and improves efficiency.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Organized a bedroom made it easier to locate personal items.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Organized a kitchen countertop cleared space for cooking.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Organized the wardrobe sorted all clothes by color and type.", 
     {"entities": [(0, 10, "SKILL")]}),
    ("Organized office drawers improved accessibility and tidiness.", 
     {"entities": [(0, 10, "SKILL")]}),

    # decluttering
    ("Decluttering the study desk removes unnecessary items and improves focus.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Decluttering of the living room area enhances space and tidiness.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Decluttering the pantry organizes all items for easy access.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Decluttering of office cabinets improves work efficiency and space.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Decluttered a bedroom removed unused furniture and items.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Decluttered a kitchen cleared shelves and counters of unnecessary items.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Decluttered the wardrobe sorted and removed unused clothes.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Decluttered office drawers organized all items and removed trash.", 
     {"entities": [(0, 12, "SKILL")]}),
]
