train_data = [
    # ----------- Laundry -----------

    # clothes sorting
    ("Clothes sorting helps separate whites and colors before washing.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Clothes sortings are necessary to prevent color bleeding in laundry.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Sorting cloth ensures garments are cleaned appropriately.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Sorting clothes properly reduces damage during washing cycles.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Sorting of clothes is essential for efficient laundry management.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Sorted cloth before washing prevents color transfer.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Sorted a cloth separated delicate items from heavy fabrics.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Sorted a clothes organized laundry before starting the wash.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Sorted cloth arranged garments by type and color for washing.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Sorted clothes ensured proper washing procedures for each fabric.", 
     {"entities": [(0, 14, "SKILL")]}),

    # hand washing
    ("Hand washing is necessary for delicate fabrics to prevent damage.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Washing by hand ensures that fragile clothes are cleaned gently.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Washing of clothes by hand helps maintain fabric quality.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Hand washed delicate shirts to prevent them from shrinking.", 
     {"entities": [(0, 11, "SKILL")]}),
    ("Hand washed a sweater carefully to avoid damage.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Hand washed clothes properly to remove stains effectively.", 
     {"entities": [(0, 14, "SKILL")]}),

    # hand washing delicates
    ("Hand washing delicates requires extra care to prevent fabric damage.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Hand washing delicate items helps maintain their shape and softness.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Washing delicates by hand is essential for silk and wool garments.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Washing a delicate by hand ensures that fragile fabrics stay intact.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Hand washed a delicate sweater carefully to avoid damage.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Hand washed delicates like silk scarves and lace tops.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Hand washed delicate fabrics separately to prevent color bleeding.", 
     {"entities": [(0, 21, "SKILL")]}),

    # ironing
    ("Ironing helps remove wrinkles from freshly washed clothes.", 
     {"entities": [(0, 7, "SKILL")]}),
    ("Ironing of cloth ensures garments look neat and professional.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Ironing of clothes prevents creases and maintains fabric shape.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Ironed a cloth before folding it into the wardrobe.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Ironed a clothes to remove wrinkles and make them presentable.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Ironed cloth carefully to avoid damaging delicate fabrics.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Ironed clothes thoroughly for a crisp, professional appearance.", 
     {"entities": [(0, 14, "SKILL")]}),

    # stain removal
    ("Stain removal is essential to keep carpets and fabrics looking clean.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Removing stain from upholstery requires proper cleaning techniques.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removing of stains from curtains keeps them bright and fresh.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Removing of stain from delicate fabrics should be done carefully.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Removed a stain from the carpet using a gentle cleaning solution.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removed stains from the sofa before the guests arrived.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removed stain from the curtain without damaging the fabric.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Removed a stains from delicate upholstery carefully.", 
     {"entities": [(0, 15, "SKILL")]}),
]
