import random
import spacy
from spacy.training import Example
from spacy.util import minibatch
import warnings
test_texts = [
     "Joanne installed a toilet.",
     "Johnatan knows how to do air conditioner repairs.",
     "I am doing LED light installations",
     "Jessica is well known for her skill as a carpenter, she is good at vacuuming carpet floor in Parañaque since 2000"
     "I was once a plumber that commonly does drain unclogging.",
     "Nicholas Andrei Yee is good in installing toilet",
     "Adrian Cuarteros is a skilled electrician",
     "John Smith performed deep cleaning services",
     "The plumber is currently performing sink maintenance",
     "Jericho is a good plumber he is knowledgable in toilet installation he started his profession January 2012",
     "Unclogging sinks requires proper tools and careful handling.",
     "The plumber replaced a sink in the new kitchen.",
     "I worked as a plumber starting from January 2020 - January 2025",
     "James is working as an electrician since February 15, 2004 in Makati",
     "Ryan installed a toilet at Manila",
     "Jericho is hired as a plumber in AWS inc. in March 2005",
     "I worked from January 2020 to March 2025",
     "Available starting next Monday",
     "Service completed on 15 January 2024",
     "From 2019 until 2023 in New York City"
]

improved_nlp = spacy.load('lg_combined_ner_model_optimized1')

# Normalization of Skill
skill_normalization = {
#Toilet Maintenance:
    'toilet installation' : 'Toilet Installation',
    'toilet installations' : 'Toilet Installation',
    'installation of toilet' : 'Toilet Installation',
    'installation of toilets': 'Toilet Installation',
    'installing of toilet': 'Toilet Installation',
    'installing of toilets': 'Toilet Installation',
    'installing toilet': 'Toilet Installation',
    'installing toilets': 'Toilet Installation',
    'installed a toilet': 'Toilet Installation',
    'installed a toilets': 'Toilet Installation',
    'installed toilet': 'Toilet Installation',
    'installed toilets': 'Toilet Installation',

    'toilet repair' : 'Toilet Repair',
    'toilet repairs' : 'Toilet Repair',
    'repairing toilet' : 'Toilet Repair',
    'repairing toilets' : 'Toilet Repair',
    'repairing of toilet' : 'Toilet Repair',
    'repairing of toilets' : 'Toilet Repair',
    'repaired toilet' : 'Toilet Repair',
    'repaired a toilet' : 'Toilet Repair',
    'repaired a toilets' : 'Toilet Repair',
    'leak fixing':'Leak Fixing',
    'fixing leak':'Leak Fixing',
    'fixing leaks':'Leak Fixing',
    'fixing of leak':'Leak Fixing',
    'fixing of leaks':'Leak Fixing',
    'fixed a leak':'Leak Fixing',
    'fixed a leaks':'Leak Fixing',
    'fixed leak':'Leak Fixing',
    'fixed leaks':'Leak Fixing',

    'toilet unclogging':'Toilet Unclogging',
    'toilet uncloggings':'Toilet Unclogging',
    'unclogging toilet':'Toilet Unclogging',
    'unclogging toilets':'Toilet Unclogging',
    'unclogging of toilet':'Toilet Unclogging',
    'unclogging of toilets':'Toilet Unclogging',
    'unclogged toilet':'Toilet Unclogging',
    'unclogged toilets':'Toilet Unclogging',
    'unclogged a toilet':'Toilet Unclogging',
    'unclogged a toilets':'Toilet Unclogging',

    'flushing system repair':'Flushing System Repair',
    'flushing systems repair':'Flushing System Repair',
    'repairing flushing system':'Flushing System Repair',
    'repairing flushing systems':'Flushing System Repair',
    'repairing of flushing system':'Flushing System Repair',
    'repairing of flushing systems':'Flushing System Repair',
    'repaired flushing system':'Flushing System Repair',
    'repaired flushing systems':'Flushing System Repair',
    'repaired a flushing system':'Flushing System Repair',
    'repaired a flushing systems':'Flushing System Repair',

    'toilet replacement':'Toilet Replacement',
    'toilet replacements':'Toilet Replacement',
    'replacing toilet':'Toilet Replacement',
    'replacing toilets':'Toilet Replacement',
    'replacing of toilet':'Toilet Replacement',
    'replacing of toilets':'Toilet Replacement',
    'replaced toilet':'Toilet Replacement',
    'replaced toilet':'Toilet Replacement',
    'replaced a toilet':'Toilet Replacement',
    'replaced a toilets':'Toilet Replacement',

#Faucet Maintenance
    'faucet installation' : 'Faucet Installation',
    'installing faucet' : 'Faucet Installation',
    'installing faucets' : 'Faucet Installation',
    'installing of faucet' : 'Faucet Installation',
    'installing of faucets' : 'Faucet Installation',
    'installation of faucet' : 'Faucet Installation',
    'installation of faucets' : 'Faucet Installation',
    'installed a faucet' : 'Faucet Installation',
    'installed a faucets' : 'Faucet Installation',
    'installed faucet' : 'Faucet Installation',
    'installed faucets' : 'Faucet Installation',

    'faucet repair' : 'Faucet Repair',
    'faucet repairs' : 'Faucet Repair',
    'repairing faucet' : 'Faucet Repair',
    'repairing faucets' : 'Faucet Repair',
    'repairing of faucet' : 'Faucet Repair',
    'repairing of faucets' : 'Faucet Repair',
    'repaired a faucet' : 'Faucet Repair',
    'repaired a faucets' : 'Faucet Repair',
    'repaired faucet' : 'Faucet Repair',
    'repaired faucets' : 'Faucet Repair',
    
    'faucet replacement' : 'Faucet Replacement',
    'faucet replacements' : 'Faucet Replacement',
    'replacing faucet' : 'Faucet Replacement',
    'replacing faucets' : 'Faucet Replacement',
    'replacing of faucet' : 'Faucet Replacement',
    'replacing of faucets' : 'Faucet Replacement',
    'replaced faucet' : 'Faucet Replacement',
    'replaced faucets' : 'Faucet Replacement',
    'replaced a faucet' : 'Faucet Replacement',
    'replaced a faucets' : 'Faucet Replacement',
    'sink installation' : 'Faucet Installation',
    'sink installations' : 'Faucet Installation',
    'installing sink' : 'Faucet Installation',
    'installing sinks' : 'Faucet Installation',
    'installing of sink' : 'Faucet Installation',
    'installing of sinks' : 'Faucet Installation',
    'installation of sink' : 'Faucet Installation',
    'installation of sinks' : 'Faucet Installation',
    'installed a sink' : 'Faucet Installation',
    'installed a sinks' : 'Faucet Installation',
    'installed sink' : 'Faucet Installation',
    'installed sinks' : 'Faucet Installation',

    'sink installation' : 'Sink Installation',
    'sink installations' : 'Sink Installation',
    'installing sink' : 'Sink Installation',
    'installing sinks' : 'Sink Installation',
    'installing of sink' : 'Sink Installation',
    'installing of sinks' : 'Sink Installation',
    'installation of sink' : 'Sink Installation',
    'installation of sinks' : 'Sink Installation',
    'installed a sink' : 'Sink Installation',
    'installed a sinks' : 'Sink Installation',
    'installed sink' : 'Sink Installation',
    'installed sinks' : 'Sink Installation',

    'sink replacement' : 'Sink Replacement',
    'sink replacements' : 'Sink Replacement',
    'replacing sink' : 'Sink Replacement',
    'replacing sinks' : 'Sink Replacement',
    'replacement of sink' : 'Sink Replacement',
    'replacement of sinks' : 'Sink Replacement',
    'replacing of sink' : 'Sink Replacement',
    'replacing of sinks' : 'Sink Replacement',
    'replaced a sink' : 'Sink Replacement',
    'replaced a sinks' : 'Sink Replacement',
    'replaced sink' : 'Sink Replacement',
    'replaced sinks' : 'Sink Replacement',

    'sink unclogging' : 'Unclogging Sink',
    'unclogging sink' : 'Unclogging Sink',
    'unclogging sinks' : 'Unclogging Sink',
    'unclogging of sink' : 'Unclogging Sink',
    'unclogging of sinks' : 'Unclogging Sink',
    'unclogged a sink' : 'Unclogging Sink',
    'unclogged sink' : 'Unclogging Sink',
    'unclogged sinks' : 'Unclogging Sink',
    
#Drain Unclogging
    'drain cleaning' : 'Drain Cleaning',
    'drain cleanings' : 'Drain Cleaning',
    'cleaning drain' : 'Drain Cleaning',
    'cleaning drains' : 'Drain Cleaning',
    'cleaning of drain' : 'Drain Cleaning',
    'cleaning of drains' : 'Drain Cleaning',
    'cleaned a drain' : 'Drain Cleaning',
    'cleaned a drains' : 'Drain Cleaning',
    'cleaned drain' : 'Drain Cleaning',
    'cleaned drains' : 'Drain Cleaning',

    'drain snaking' : 'Drain Snaking',
    'drain snakings' : 'Drain Snaking',
    'snaking drain' : 'Drain Snaking',
    'snaking drains' : 'Drain Snaking',
    'snaking of drain' : 'Drain Snaking',
    'snaking of drains' : 'Drain Snaking',
    'snaked a drain' : 'Drain Snaking',
    'snaked a drains' : 'Drain Snaking',
    'snaked drain' : 'Drain Snaking',
    'snaked drains' : 'Drain Snaking',
    'drain repair' : 'Drain Snaking',

    'hydro jetting' : 'Hydro Jetting',

    'clog removal' : 'Clog Removal',
    'removal of clog' : 'Clog Removal',
    'removal of clogs' : 'Clog Removal',
    'removing clog' : 'Clog Removal',
    'removing clogs' : 'Clog Removal',
    'removing of clog' : 'Clog Removal',
    'removing of clogs' : 'Clog Removal',
    'removed a clog' : 'Clog Removal',
    'removed a clogs' : 'Clog Removal',
    'removed clog' : 'Clog Removal',
    'removed clogs' : 'Clog Removal',

#Shower Maintenance:
    'showerhead installation' : 'Showerhead Installation',
    'showerhead installations' : 'Showerhead Installation',
    'installation of showerhead' : 'Showerhead Installation',
    'installation of showerheads' : 'Showerhead Installation',
    'installing of showerhead' : 'Showerhead Installation',
    'installing of showerheads' : 'Showerhead Installation',
    'installing showerhead' : 'Showerhead Installation',
    'installing showerheads' : 'Showerhead Installation',
    'installed showerhead' : 'Showerhead Installation',
    'installed showerheads' : 'Showerhead Installation',
    'installed a showerhead' : 'Showerhead Installation',
    'installed a showerheads' : 'Showerhead Installation',

    'showerhead repair' : 'Repairing Showerhead',
    'showerhead repairs' : 'Repairing Showerhead',
    'repairing showerhead' : 'Repairing Showerhead',
    'repairing showerheads' : 'Repairing Showerhead',
    'repairing of showerhead' : 'Repairing Showerhead',
    'repairing of showerheads' : 'Repairing Showerhead',
    'repaired a showerhead' : 'Repairing Showerhead',
    'repaired a showerheads' : 'Repairing Showerhead',
    'repaired showerhead' : 'Repairing Showerhead',
    'repaired showerheads' : 'Repairing Showerhead',

    'valve replacement' : 'Valve Replacement',
    'valve replacements' : 'Valve Replacement',
    'replacing valve' : 'Valve Replacement',
    'replacing valves' : 'Valve Replacement',
    'replacing of valve' : 'Valve Replacement',
    'replacing of valves' : 'Valve Replacement',
    'replacement of valve' : 'Valve Replacement',
    'replacement of valves' : 'Valve Replacement',
    'replaced a valve' : 'Valve Replacement',
    'replaced a valves' : 'Valve Replacement',
    'replaced valve' : 'Valve Replacement',
    'replaced valves' : 'Valve Replacement',

    'shower pipe repair' : 'Shower Pipe Repair',
    'shower pipe repairs' : 'Shower Pipe Repair',
    'repairing shower pipe' : 'Shower Pipe Repair',
    'repairing shower pipes' : 'Shower Pipe Repair',
    'repairing of shower pipe' : 'Shower Pipe Repair',
    'repairing of shower pipes' : 'Shower Pipe Repair',
    'repaired a shower pipe' : 'Shower Pipe Repair',
    'repaired a shower pipes' : 'Shower Pipe Repair',
    'repaired shower pipe' : 'Shower Pipe Repair',
    'repaired shower pipes' : 'Shower Pipe Repair',

    'shower pipe repair' : 'Shower Pipe Repair',
    'shower pipe repairs' : 'Shower Pipe Repair',
    'repairing shower pipe' : 'Shower Pipe Repair',
    'repairing shower pipes' : 'Shower Pipe Repair',
    'repairing of shower pipe' : 'Shower Pipe Repair',
    'repairing of shower pipes' : 'Shower Pipe Repair',
    'repaired a shower pipe' : 'Shower Pipe Repair',
    'repaired a shower pipes' : 'Shower Pipe Repair',
    'repaired shower pipe' : 'Shower Pipe Repair',
    'repaired shower pipes' : 'Shower Pipe Repair',

#Bathtub Maintenance
    'bathtub installation' : 'Bathtub Installation',
    'bathtub installations' : 'Bathtub Installation',
    'installing bathtub' : 'Bathtub Installation',
    'installing bathtubs' : 'Bathtub Installation',
    'installation of bathtub' : 'Bathtub Installation',
    'installation of bathtubs' : 'Bathtub Installation',
    'installing of bathtub' : 'Bathtub Installation',
    'installing of bathtubs' : 'Bathtub Installation',

    'bathtub repair' : 'Bathtub Repair',
    'bathtub repairs' : 'Bathtub Repair',
    'repairing bathtub' : 'Bathtub Repair',
    'repairing bathtubs' : 'Bathtub Repair',
    'repairing of bathtub' : 'Bathtub Repair',
    'repairing of bathtubs' : 'Bathtub Repair',
    'repaired a bathtub' : 'Bathtub Repair',
    'repaired a bathtubs' : 'Bathtub Repair',
    'repaired bathtub' : 'Bathtub Repair',
    'repaired bathtubs' : 'Bathtub Repair',

    'fixture replacement' : 'Fixture Replacement',
    'fixture replacements' : 'Fixture Replacement',
    'replacing fixture' : 'Fixture Replacement',
    'replacing fixtures' : 'Fixture Replacement',
    'replacing of fixture' : 'Fixture Replacement',
    'replacing of fixtures' : 'Fixture Replacement',
    'replacement of fixture' : 'Fixture Replacement',
    'replacement of fixtures' : 'Fixture Replacement',
    'replaced a fixture' : 'Fixture Replacement',
    'replaced a fixtures' : 'Fixture Replacement',
    'replaced fixture' : 'Fixture Replacement',
    'replaced fixtures' : 'Fixture Replacement',

    'caulking and sealing' : 'Caulking and Sealing',
    'sealing and caulking' : 'Caulking and Sealing',
    'caulking of gap' : 'Caulking and Sealing',
    'caulking of gaps' : 'Caulking and Sealing',
    'caulked a gap' : 'Caulking and Sealing',
    'caulked a gaps' : 'Caulking and Sealing',
    'caulked gap' : 'Caulking and Sealing',
    'caulked gaps' : 'Caulking and Sealing',
    'gap caulking' : 'Caulking and Sealing',
    'sealing of gap' : 'Caulking and Sealing',
    'sealing of gaps' : 'Caulking and Sealing',
    'sealed a gap' : 'Caulking and Sealing',
    'sealed a gaps' : 'Caulking and Sealing',
    'sealed gap' : 'Caulking and Sealing',
    'sealed gaps' : 'Caulking and Sealing',
    'gap sealing' : 'Caulking and Sealing',

    'drain repairs' : 'Drain Repairs',
    'repairing drain' : 'Drain Repairs',
    'repairing drains' : 'Drain Repairs',
    'repairing of drain' : 'Drain Repairs',
    'repairing of drains' : 'Drain Repairs',
    'repaired a drain' : 'Drain Repairs',
    'repaired a drains' : 'Drain Repairs',
    'repaired drain' : 'Drain Repairs',
    'repaired drains' : 'Drain Repairs',

#Pipe Repair 
    'leak detection' : 'Leak Detection',
    'leak detections' : 'Leak Detection',
    'detection of leak' : 'Leak Detection',
    'detection of leaks' : 'Leak Detection',
    'detecting of leak' : 'Leak Detection',
    'detecting of leaks' : 'Leak Detection',
    'detecting leak' : 'Leak Detection',
    'detecting leaks' : 'Leak Detection',
    'detected a leak' : 'Leak Detection',
    'detected a leaks' : 'Leak Detection',
    'detected leak' : 'Leak Detection',
    'detected leaks' : 'Leak Detection',

    'pipe cutting' : 'Pipe Cutting',
    'cutting pipe' : 'Pipe Cutting',
    'cutting pipes' : 'Pipe Cutting',
    'cutting of pipe' : 'Pipe Cutting',
    'cutting of pipes' : 'Pipe Cutting',
    'cut a pipe' : 'Pipe Cutting',
    'cut a pipes' : 'Pipe Cutting',
    'cut pipe' : 'Pipe Cutting',
    'cut pipes' : 'Pipe Cutting',

    'pipe fitting' : 'Pipe Fitting',
    'pipe fittings' : 'Pipe Fitting',
    'fitting pipe' : 'Pipe Fitting',
    'fitting pipes' : 'Pipe Fitting',
    'fitting of pipe' : 'Pipe Fitting',
    'fitting of pipes' : 'Pipe Fitting',
    'fitted a pipe' : 'Pipe Fitting',
    'fitted a pipes' : 'Pipe Fitting',
    'fitted pipe' : 'Pipe Fitting',
    'fitted pipes' : 'Pipe Fitting',

    'pipe replacement' : 'Pipe Replacement',
    'pipe replacements' : 'Pipe Replacement',

    'replacing pipe' : 'Replacing Pipe',
    'replacing pipes' : 'Replacing Pipe',
    'replacing of pipe' : 'Replacing Pipe',
    'replacing of pipes' : 'Replacing Pipe',
    'replacement of pipe' : 'Replacing Pipe',
    'replacement of pipes' : 'Replacing Pipe',
    'replaced a pipe' : 'Replacing Pipe',
    'replaced a pipes' : 'Replacing Pipe',
    'replaced pipe' : 'Replacing Pipe',
    'replaced pipes' : 'Replacing Pipe',

    'pipe welding' : 'Pipe Welding',
    'pipe weldings' : 'Pipe Welding',
    'welding pipe' : 'Pipe Welding',
    'welding pipes' : 'Pipe Welding',
    'welding of pipe' : 'Pipe Welding',
    'welding of pipes' : 'Pipe Welding',
    'welded a pipe' : 'Pipe Welding',
    'welded a pipes' : 'Pipe Welding',
    'welded pipe' : 'Pipe Welding',
    'welded pipes' : 'Pipe Welding',

    'joint sealing' : 'Joint Sealing',
    'joint sealings' : 'Joint Sealing',
    'sealing joint' : 'Joint Sealing',
    'sealing joints' : 'Joint Sealing',
    'sealing of joint' : 'Joint Sealing',
    'sealing of joints' : 'Joint Sealing',
    'sealed a joint' : 'Joint Sealing',
    'sealed a joints' : 'Joint Sealing',
    'sealed joint' : 'Joint Sealing',
    'sealed joints' : 'Joint Sealing',

#Waterline Maintenance
    'water line installation' : 'Water Line Installation',
    'water line installations' : 'Water Line Installation',
    'installation of water line' : 'Water Line Installation',
    'installation of water lines' : 'Water Line Installation',
    'installing of water line' : 'Water Line Installation',
    'installing of water lines' : 'Water Line Installation',
    'installed a water line' : 'Water Line Installation',
    'installed a water lines' : 'Water Line Installation',
    'installed water line' : 'Water Line Installation',
    'installed water lines' : 'Water Line Installation',

    'pipe fitting' : 'Pipe Fitting',
    'pipe fittings' : 'Pipe Fitting',
    'fitting pipe' : 'Pipe Fitting',
    'fitting pipes' : 'Pipe Fitting',
    'fitting of pipe' : 'Pipe Fitting',
    'fitting of pipes' : 'Pipe Fitting',
    'fitted a pipe' : 'Pipe Fitting',
    'fitted a pipes' : 'Pipe Fitting',
    'fitted pipe' : 'Pipe Fitting',
    'fitted pipes' : 'Pipe Fitting',

    'pipe replacement' : 'Pipe Replacement',
    'pipe replacements' : 'Pipe Replacement',

    'pipe connection' : 'Pipe Connection',
    'pipe connections' : 'Pipe Connection',
    'connecting pipe' : 'Pipe Connection',
    'connecting pipes' : 'Pipe Connection',
    'connecting of pipe' : 'Pipe Connection',
    'connecting of pipes' : 'Pipe Connection',
    'connection of pipe' : 'Pipe Connection',
    'connection of pipes' : 'Pipe Connection',
    'connected a pipe' : 'Pipe Connection',
    'connected a pipes' : 'Pipe Connection',
    'connected pipe' : 'Pipe Connection',
    'connected pipes' : 'Pipe Connection',

    'water line repair' : 'Water Line Repair',
    'water line repairs' : 'Water Line Repair',
    'repairing water line' : 'Water Line Repair',
    'repairing water lines' : 'Water Line Repair',
    'repairing of water line' : 'Water Line Repair',
    'repairing of water lines' : 'Water Line Repair',
    'repaired a water line' : 'Water Line Repair',
    'repaired a water lines' : 'Water Line Repair',
    'repaired water line' : 'Water Line Repair',
    'repaired water lines' : 'Water Line Repair',

    'pressure testing' : 'Pressure Testing',
    'pressure testings' : 'Pressure Testing',
    'pressure tester' : 'Pressure Testing',
    'pressure testers' : 'Pressure Testing',
    'pressure test' : 'Pressure Testing',
    'pressure tests' : 'Pressure Testing',
    'testing of water pressure' : 'Pressure Testing',
    'testing of water pressures' : 'Pressure Testing',
    'tested a water pressure' : 'Pressure Testing',
    'tested a water pressures' : 'Pressure Testing',
    'water pressure testing' : 'Pressure Testing',
    'water pressure testings' : 'Pressure Testing',
    'water pressure tester' : 'Pressure Testing',
    'water pressure testers' : 'Pressure Testing',
    'testing of pressure' : 'Pressure Testing',
    'testing of pressures' : 'Pressure Testing',
    'testing pressure' : 'Pressure Testing',
    'testing pressures' : 'Pressure Testing',
    'tested pressure' : 'Pressure Testing',
    'tested pressures' : 'Pressure Testing',

#Water Heater Maintenance
    'sediment flushing' : 'Sediment Flushing',
    'sediment flusher' : 'Sediment Flushing',
    'sediment flushers' : 'Sediment Flushing',
    'flushing sediment' : 'Sediment Flushing',
    'flushing sediments' : 'Sediment Flushing',
    'flushing of sediment' : 'Sediment Flushing',
    'flushing of sediments' : 'Sediment Flushing',
    'flushed a sediment' : 'Sediment Flushing',
    'flushed a sediments' : 'Sediment Flushing',
    'flushed sediment' : 'Sediment Flushing',
    'flushed sediments' : 'Sediment Flushing',

    'thermostat adjustment' : 'Thermostat Adjustment',
    'thermostat adjustments' : 'Thermostat Adjustment',
    'adjusting thermostat' : 'Thermostat Adjustment',
    'adjusting thermostats' : 'Thermostat Adjustment',
    'adjusting of thermostat' : 'Thermostat Adjustment',
    'adjusting of thermostats' : 'Thermostat Adjustment',
    'adjusted a thermostat' : 'Thermostat Adjustment',
    'adjusted a thermostats' : 'Thermostat Adjustment',
    'adjusted thermostat' : 'Thermostat Adjustment',
    'adjusted thermostats' : 'Thermostat Adjustment',
    
#Lighting Maintenance
    'incandescent light installation' : 'Incandescent Light Installation',
    'incandescent light installations' : 'Incandescent Light Installation',
    'installation of incandescent light' : 'Incandescent Light Installation',
    'installation of incandescent lights' : 'Incandescent Light Installation',
    'installing incandescent light' : 'Incandescent Light Installation',
    'installing incandescent lights' : 'Incandescent Light Installation',
    'installing of incandescent light' : 'Incandescent Light Installation',
    'installing of incandescent lights' : 'Incandescent Light Installation',
    'installed a incandescent light' : 'Incandescent Light Installation',
    'installed a incandescent lights' : 'Incandescent Light Installation',
    'installed incandescent light' : 'Incandescent Light Installation',
    'installed incandescent lights' : 'Incandescent Light Installation',

    'fluorescent light installation' : 'Fluorescent Light Installation',
    'fluorescent light installations' : 'Fluorescent Light Installation',
    'installation of fluorescent light' : 'Fluorescent Light Installation',
    'installation of fluorescent lights' : 'Fluorescent Light Installation',
    'installing fluorescent light' : 'Fluorescent Light Installation',
    'installing fluorescent lights' : 'Fluorescent Light Installation',
    'installing of fluorescent light' : 'Fluorescent Light Installation',
    'installing of fluorescent lights' : 'Fluorescent Light Installation',
    'installed a fluorescent light' : 'Fluorescent Light Installation',
    'installed a fluorescent lights' : 'Fluorescent Light Installation',
    'installed fluorescent light' : 'Fluorescent Light Installation',
    'installed fluorescent lights' : 'Fluorescent Light Installation',

    'led light installation' : 'LED Light Installation',
    'led light installations' : 'LED Light Installation',
    'installation of led light' : 'LED Light Installation',
    'installation of led lights' : 'LED Light Installation',
    'installing of led light' : 'LED Light Installation',
    'installing of led lights' : 'LED Light Installation',
    'installing led light' : 'LED Light Installation',
    'installing led lights' : 'LED Light Installation',
    'installed led light' : 'LED Light Installation',
    'installed led lights' : 'LED Light Installation',
    'installed a led light' : 'LED Light Installation',
    'installed a led lights' : 'LED Light Installation',

    'bulb replacement' : 'Bulb Replacement',
    'bulb replacements' : 'Bulb Replacement',
    'replacing bulb' : 'Bulb Replacement',
    'replacing bulbs' : 'Bulb Replacement',
    'replacing of bulb' : 'Bulb Replacement',
    'replacing of bulbs' : 'Bulb Replacement',
    'replacement of bulb' : 'Bulb Replacement',
    'replacement of bulbs' : 'Bulb Replacement',
    'replaced a bulb' : 'Bulb Replacement',
    'replaced a bulbs' : 'Bulb Replacement',
    'replaced bulb' : 'Bulb Replacement',
    'replaced bulbs' : 'Bulb Replacement',

    'light fixture installation' : 'Light Fixture Installation',
    'light fixture installations' : 'Light Fixture Installation',
    'installation of light fixture' : 'Light Fixture Installation',
    'installation of light fixtures' : 'Light Fixture Installation',
    'installing of light fixture' : 'Light Fixture Installation',
    'installing of light fixtures' : 'Light Fixture Installation',
    'installing light fixture' : 'Light Fixture Installation',
    'installing light fixtures' : 'Light Fixture Installation',
    'installed light fixture' : 'Light Fixture Installation',
    'installed light fixtures' : 'Light Fixture Installation',
    'installed a light fixture' : 'Light Fixture Installation',

#Electrical Wiring and Rewiring
    'wire installation' : 'Wire Installation',
    'wire installations' : 'Wire Installation',
    'installation of wire' : 'Wire Installation',
    'installation of wires' : 'Wire Installation',
    'installing of wire' : 'Wire Installation',
    'installing of wires' : 'Wire Installation',
    'installing wire' : 'Wire Installation',
    'installing wires' : 'Wire Installation',
    'installed wire' : 'Wire Installation',
    'installed wires' : 'Wire Installation',
    'installed a wire' : 'Wire Installation',
    'installed a wires' : 'Wire Installation',

    'conduit installation' : 'Conduit Installation',
    'conduit installations' : 'Conduit Installation',
    'installation of conduit' : 'Conduit Installation',
    'installation of conduits' : 'Conduit Installation',
    'installing of conduit' : 'Conduit Installation',
    'installing of conduits' : 'Conduit Installation',
    'installing conduit' : 'Conduit Installation',
    'installing conduits' : 'Conduit Installation',
    'installed conduit' : 'Conduit Installation',
    'installed conduits' : 'Conduit Installation',
    'installed a conduit' : 'Conduit Installation',
    'installed a conduits' : 'Conduit Installation',

    'electrical insulation' : 'Electrical Insulation',
    'insulation of electrical wiring' : 'Electrical Insulation',
    'insulation of electrical wirings' : 'Electrical Insulation',
    'insulating electrical wiring' : 'Electrical Insulation',
    'insulating electrical wirings' : 'Electrical Insulation',
    'insulating of electrical wiring' : 'Electrical Insulation',
    'insulating of electrical wirings' : 'Electrical Insulation',
    'insulated a electrical wiring' : 'Electrical Insulation',
    'insulated a electrical wirings' : 'Electrical Insulation',
    'insulated electrical wiring' : 'Electrical Insulation',
    'insulated electrical wirings' : 'Electrical Insulation',

    'circuit connection' : 'Circuit Connection',
    'circuit connections' : 'Circuit Connection',
    'connecting circuit' : 'Circuit Connection',
    'connecting circuits' : 'Circuit Connection',
    'connecting of circuit' : 'Circuit Connection',
    'connecting of circuits' : 'Circuit Connection',
    'connection of circuit' : 'Circuit Connection',
    'connection of circuits' : 'Circuit Connection',
    'connected a circuit' : 'Circuit Connection',
    'connected a circuits' : 'Circuit Connection',
    'connected circuit' : 'Circuit Connection',
    'connected circuits' : 'Circuit Connection',

#Washing Machine Maintenance
    'washing machine repair' : 'Washing Machine Repair',
    'washing machine repairs' : 'Washing Machine Repair',
    'repairing washing machine' : 'Washing Machine Repair',
    'repairing washing machines' : 'Washing Machine Repair',
    'repaired washing machines' : 'Washing Machine Repair',
    'repaired a washing machine' : 'Washing Machine Repair',
    'repaired a washing machines' : 'Washing Machine Repair',
    'repairing of washing machine' : 'Washing Machine Repair',
    'repairing of washing machines' : 'Washing Machine Repair',

    'belt replacement' : 'Belt Replacement',
    'belt replacements' : 'Belt Replacement',
    'replacement of belt' : 'Belt Replacement',
    'replacement of belts' : 'Belt Replacement',
    'replacement of washing machine belt' : 'Belt Replacement',
    'replacement of washing machine belts' : 'Belt Replacement',
    'replacing washing machine belt' : 'Belt Replacement',
    'replacing washing machine belts' : 'Belt Replacement',
    'replacing of washing machine belt' : 'Belt Replacement',
    'replacing of washing machine belts' : 'Belt Replacement',
    'replacing belt' : 'Belt Replacement',
    'replacing belts' : 'Belt Replacement',
    'replacing of belt' : 'Belt Replacement',
    'replacing of belts' : 'Belt Replacement',
    'replaced a washing machine belt' : 'Belt Replacement',
    'replaced a washing machine belts' : 'Belt Replacement',
    'replaced washing machine belt' : 'Belt Replacement',
    'replaced washing machine belts' : 'Belt Replacement',

    'drum cleaning' : 'Drum Cleaning',
    'cleaning drum' : 'Drum Cleaning',
    'cleaning drums' : 'Drum Cleaning',
    'cleaned drum' : 'Drum Cleaning',
    'cleaned drums' : 'Drum Cleaning',
    'cleaned washing machine drum' : 'Drum Cleaning',
    'cleaned washing machine drums' : 'Drum Cleaning',
    'cleaned a washing machine drum' : 'Drum Cleaning',
    'cleaned a washing machine drums' : 'Drum Cleaning',
    'washing machine drum cleaning' : 'Drum Cleaning',
    'cleaning of washing machine drum' : 'Drum Cleaning',
    'cleaning of washing machine drums' : 'Drum Cleaning',
    'cleaning of drum' : 'Drum Cleaning',
    'cleaning of drums' : 'Drum Cleaning',
    'cleaned a drum' : 'Drum Cleaning',
    'cleaned a drums' : 'Drum Cleaning',

    'hose replacement' : 'Hose Replacement',
    'hose replacements' : 'Hose Replacement',
    'replacing hose' : 'Hose Replacement',
    'replacing hoses' : 'Hose Replacement',
    'replacing of hose' : 'Hose Replacement',
    'replacing of hoses' : 'Hose Replacement',
    'replacing of washing machine hose' : 'Hose Replacement',
    'replacing of washing machine hoses' : 'Hose Replacement',
    'replacement of washing machine hose' : 'Hose Replacement',
    'replacement of washing machine hoses' : 'Hose Replacement',
    'replacement of hose' : 'Hose Replacement',
    'replacement of hoses' : 'Hose Replacement',

    'washing machine hose installation' : 'Hose Installation',
    'washing machine hose installations' : 'Hose Installation',
    'installation of washing machine hose' : 'Hose Installation',
    'installation of washing machine hoses' : 'Hose Installation',
    'installment of washing machine hose' : 'Hose Installation',
    'installment of washing machine hoses' : 'Hose Installation',
    'installing washing machine hose' : 'Hose Installation',
    'installing washing machine hoses' : 'Hose Installation',
    'installed washing machine hose' : 'Hose Installation',
    'installed washing machine hoses' : 'Hose Installation',
    'installed a washing machine hose' : 'Hose Installation',
    'installed a washing machine hoses' : 'Hose Installation',


#Television Maintenance
    'screen replacement' : 'Screen Replacement',
    'screen replacements' : 'Screen Replacement',
    'replacing screen' : 'Screen Replacement',
    'replacing screens' : 'Screen Replacement',
    'replacing of screen' : 'Screen Replacement',
    'replacing of screens' : 'Screen Replacement',
    'replaced a screen' : 'Screen Replacement',
    'replaced a screens' : 'Screen Replacement',
    'replaced screen' : 'Screen Replacement',
    'replaced screens' : 'Screen Replacement',
    'replacement of screen' : 'Screen Replacement',
    'replacement of screens' : 'Screen Replacement',

    'screen repair' : 'Screen Repair',
    'screen repairing' : 'Screen Repair',
    'repairing screen' : 'Screen Repair',
    'repairing screens' : 'Screen Repair',
    'repairing of screen' : 'Screen Repair',
    'repairing of screens' : 'Screen Repair',
    'repaired a screen' : 'Screen Repair',
    'repaired a screens' : 'Screen Repair',
    'repaired screen' : 'Screen Repair',
    'repaired screens' : 'Screen Repair',

    'remote sensor repair' : 'Remote Sensor Repair',
    'remote sensor repairs' : 'Remote Sensor Repair',
    'remote sensor repairing' : 'Remote Sensor Repair',
    'repairing remote sensor' : 'Remote Sensor Repair',
    'repairing remote sensors' : 'Remote Sensor Repair',
    'repairing of remote sensor' : 'Remote Sensor Repair',
    'repairing of remote sensors' : 'Remote Sensor Repair',
    'repaired a remote sensor' : 'Remote Sensor Repair',
    'repaired a remote sensors' : 'Remote Sensor Repair',
    'repaired remote sensor' : 'Remote Sensor Repair',
    'repaired remote sensors' : 'Remote Sensor Repair',

    'power supply board repair' : 'Power Supply Board Repair',
    'power supply board repairs' : 'Power Supply Board Repair',
    'power supply board repairing' : 'Power Supply Board Repair',
    'repairing power supply board' : 'Power Supply Board Repair',
    'repairing power supply boards' : 'Power Supply Board Repair',
    'repairing of power supply board' : 'Power Supply Board Repair',
    'repairing of power supply boards' : 'Power Supply Board Repair',
    'repaired a power supply board' : 'Power Supply Board Repair',
    'repaired a power supply boards' : 'Power Supply Board Repair',
    'repaired power supply board' : 'Power Supply Board Repair',
    'repaired power supply boards' : 'Power Supply Board Repair',

    'control panel troubleshooting' : 'Control Panel Troubleshooting',
    'troubleshooting control panel' : 'Control Panel Troubleshooting',
    'troubleshooting control panels' : 'Control Panel Troubleshooting',
    'troubleshooting of control panel' : 'Control Panel Troubleshooting',
    'troubleshooting of control panels' : 'Control Panel Troubleshooting',
    'troubleshoot control panel' : 'Control Panel Troubleshooting',
    'troubleshoot control panels' : 'Control Panel Troubleshooting',
    'troubleshot control panel' : 'Control Panel Troubleshooting',
    'troubleshot control panels' : 'Control Panel Troubleshooting',
    'troubleshot a control panel' : 'Control Panel Troubleshooting',
    'troubleshot a control panels' : 'Control Panel Troubleshooting',

    'backlight replacement' : 'Backlight Replacement',
    'backlight replacements' : 'Backlight Replacement',
    'replacing backlight' : 'Backlight Replacement',
    'replacing backlights' : 'Backlight Replacement',
    'replacing of backlight' : 'Backlight Replacement',
    'replacing of backlights' : 'Backlight Replacement',
    'replaced a backlight' : 'Backlight Replacement',
    'replaced a backlights' : 'Backlight Replacement',
    'replaced backlight' : 'Backlight Replacement',
    'replaced backlights' : 'Backlight Replacement',
    'replacement of backlight' : 'Backlight Replacement',
    'replacement of backlights' : 'Backlight Replacement',

    'backlight repair' : 'Backlight Repair',
    'backlight repairs' : 'Backlight Repair',
    'repairing backlight' : 'Backlight Repair',
    'repairing backlights' : 'Backlight Repair',
    'repairing of backlight' : 'Backlight Repair',
    'repairing of backlights' : 'Backlight Repair',
    'repaired a backlight' : 'Backlight Repair',
    'repaired a backlights' : 'Backlight Repair',
    'repaired backlight' : 'Backlight Repair',
    'repaired backlights' : 'Backlight Repair',

#Electric Fan Maintenance
    'motor cleaning' : 'Motor Cleaning',
    'cleaning motor' : 'Motor Cleaning',
    'cleaning motors' : 'Motor Cleaning',
    'cleaned motor' : 'Motor Cleaning',
    'cleaned motors' : 'Motor Cleaning',
    'cleaned a motor' : 'Motor Cleaning',
    'cleaned a motors' : 'Motor Cleaning',
    'cleaning of motor' : 'Motor Cleaning',
    'cleaning of motors' : 'Motor Cleaning',

    'motor lubrication' : 'Motor Lubrication',
    'lubrication of motor' : 'Motor Lubrication',
    'lubrication of motors' : 'Motor Lubrication',
    'lubricated motor' : 'Motor Lubrication',
    'lubricated motors' : 'Motor Lubrication',
    'lubricated a motor' : 'Motor Lubrication',
    'lubricated a motors' : 'Motor Lubrication',

    'blade replacement' : 'Blade Replacement',
    'blade replacements' : 'Blade Replacement',
    'replacing blade' : 'Blade Replacement',
    'replacing blades' : 'Blade Replacement',
    'replacing of blade' : 'Blade Replacement',
    'replacing of blades' : 'Blade Replacement',
    'replaced a blade' : 'Blade Replacement',
    'replaced a blades' : 'Blade Replacement',
    'replaced blade' : 'Blade Replacement',
    'replaced blades' : 'Blade Replacement',
    'replacement of blade' : 'Blade Replacement',
    'replacement of blades' : 'Blade Replacement',

    'oscillation mechanism repair' : 'Oscillation Mechanism Repair',
    'oscillation mechanism repairs' : 'Oscillation Mechanism Repair',
    'repairing oscillation mechanism' : 'Oscillation Mechanism Repair',
    'repairing oscillation mechanisms' : 'Oscillation Mechanism Repair',
    'repairing of oscillation mechanism' : 'Oscillation Mechanism Repair',
    'repairing of oscillation mechanisms' : 'Oscillation Mechanism Repair',
    'repaired a oscillation mechanism' : 'Oscillation Mechanism Repair',
    'repaired a oscillation mechanisms' : 'Oscillation Mechanism Repair',
    'repaired oscillation mechanism' : 'Oscillation Mechanism Repair',
    'repaired oscillation mechanisms' : 'Oscillation Mechanism Repair',

    'speed control repair' : 'Speed Control Repair',
    'speed control repairs' : 'Speed Control Repair',
    'speed controller repair' : 'Speed Control Repair',
    'speed controller repairs' : 'Speed Control Repair',
    'repairing speed control' : 'Speed Control Repair',
    'repairing speed controls' : 'Speed Control Repair',
    'repairing speed controller' : 'Speed Control Repair',
    'repairing speed controllers' : 'Speed Control Repair',
    'repairing of speed control' : 'Speed Control Repair',
    'repairing of speed controls' : 'Speed Control Repair',
    'repairing of speed controller' : 'Speed Control Repair',
    'repairing of speed controllers' : 'Speed Control Repair',
    'repaired a speed control' : 'Speed Control Repair',
    'repaired a speed controls' : 'Speed Control Repair',
    'repaired a speed controller' : 'Speed Control Repair',
    'repaired a speed controllers' : 'Speed Control Repair',
    'repaired speed control' : 'Speed Control Repair',
    'repaired speed controls' : 'Speed Control Repair',
    'repaired speed controller' : 'Speed Control Repair',
    'repaired speed controllers' : 'Speed Control Repair',

    'bearing replacement' : 'Bearing Replacement',
    'bearing replacements' : 'Bearing Replacement',
    'replacing bearing' : 'Bearing Replacement',
    'replacing bearings' : 'Bearing Replacement',
    'replacing of bearing' : 'Bearing Replacement',
    'replacing of bearings' : 'Bearing Replacement',
    'replaced a bearing' : 'Bearing Replacement',
    'replaced a bearings' : 'Bearing Replacement',
    'replaced bearing' : 'Bearing Replacement',
    'replaced bearings' : 'Bearing Replacement',
    'replacement of bearing' : 'Bearing Replacement',
    'replacement of bearings' : 'Bearing Replacement',

#Refrigerator Maintenance
    'condenser coil cleaning' : 'Condenser Coil Cleaning',
    'cleaning condenser coil' : 'Condenser Coil Cleaning',
    'cleaning condenser coils' : 'Condenser Coil Cleaning',
    'cleaned condenser coil' : 'Condenser Coil Cleaning',
    'cleaned condenser coils' : 'Condenser Coil Cleaning',
    'cleaned refrigerator condenser coil' : 'Condenser Coil Cleaning',
    'cleaned refrigerator condenser coils' : 'Condenser Coil Cleaning',
    'cleaned a refrigerator condenser coil' : 'Condenser Coil Cleaning',
    'cleaned a refrigerator condenser coils' : 'Condenser Coil Cleaning',
    'cleaning of refrigerator condenser coil' : 'Condenser Coil Cleaning',
    'cleaning of refrigerator condenser coils' : 'Condenser Coil Cleaning',

    'defrost system maintenance' : 'Defrost System Maintenance',
    'maintenance of defrost system' : 'Defrost System Maintenance',
    'maintenance of defrost systems' : 'Defrost System Maintenance',
    'maintaining defrost system' : 'Defrost System Maintenance',
    'maintaining defrost systems' : 'Defrost System Maintenance',
    'maintaining of defrost system' : 'Defrost System Maintenance',
    'maintaining of defrost systems' : 'Defrost System Maintenance',
    'maintained defrost system' : 'Defrost System Maintenance',
    'maintained defrost systems' : 'Defrost System Maintenance',
    'maintained a defrost system' : 'Defrost System Maintenance',
    'maintained a defrost systems' : 'Defrost System Maintenance',

    'thermostat control checking' : 'Thermostat Control Checking',
    'checking thermostat control' : 'Thermostat Control Checking',
    'checking thermostat controls' : 'Thermostat Control Checking',
    'checking of thermostat control' : 'Thermostat Control Checking',
    'checking of thermostat controls' : 'Thermostat Control Checking',
    'checked a thermostat control' : 'Thermostat Control Checking',
    'checked a thermostat controls' : 'Thermostat Control Checking',
    'checked thermostat control' : 'Thermostat Control Checking',
    'checked thermostat controls' : 'Thermostat Control Checking',

    'ice maker repair' : 'Ice Maker Repair',
    'ice maker repairs' : 'Ice Maker Repair',
    'repairing ice maker' : 'Ice Maker Repair',
    'repairing ice makers' : 'Ice Maker Repair',
    'repairing of ice maker' : 'Ice Maker Repair',
    'repairing of ice makers' : 'Ice Maker Repair',
    'repaired a ice maker' : 'Ice Maker Repair',
    'repaired a ice makers' : 'Ice Maker Repair',
    'repaired ice maker' : 'Ice Maker Repair',
    'repaired ice makers' : 'Ice Maker Repair',

#Air Conditioner Maintenance
    'air conditioner repair' : 'Air Conditioner Repair',
    'air conditioner repairs' : 'Air Conditioner Repair',
    'repairs air conditioner' : 'Air Conditioner Repair',
    'repairs air conditioners' : 'Air Conditioner Repair',
    'repairs a air conditioner' : 'Air Conditioner Repair',
    'repairs a air conditioners' : 'Air Conditioner Repair',
    'repairing air conditioner' : 'Air Conditioner Repair',
    'repairing air conditioners' : 'Air Conditioner Repair',
    'repairing of air conditioner' : 'Air Conditioner Repair',
    'repairing of air conditioners' : 'Air Conditioner Repair',
    'repaired a air conditioner' : 'Air Conditioner Repair',
    'repaired a air conditioners' : 'Air Conditioner Repair',
    'repaired air conditioner' : 'Air Conditioner Repair',
    'repaired air conditioners' : 'Air Conditioner Repair',

    'air conditioner installation' : 'Air Conditioner Installation',
    'air conditioner installations' : 'Air Conditioner Installation',
    'installing air conditioner' : 'Air Conditioner Installation',
    'installing air conditioners' : 'Air Conditioner Installation',
    'installing of air conditioner' : 'Air Conditioner Installation',
    'installing of air conditioners' : 'Air Conditioner Installation',
    'installation of air conditioner' : 'Air Conditioner Installation',
    'installation of air conditioners' : 'Air Conditioner Installation',
    'installed a air conditioner' : 'Air Conditioner Installation',
    'installed a air conditioners' : 'Air Conditioner Installation',
    'installed air conditioner' : 'Air Conditioner Installation',
    'installed air conditioners' : 'Air Conditioner Installation',

    'coil cleaning' : 'Coil Cleaning',
    'air conditioning coil cleaning' : 'Coil Cleaning',
    'cleaning coil' : 'Coil Cleaning',
    'cleaning coils' : 'Coil Cleaning',
    'cleaned coil' : 'Coil Cleaning',
    'cleaned coils' : 'Coil Cleaning',
    'cleaned air conditioning coil' : 'Coil Cleaning',
    'cleaned air conditioning coils' : 'Coil Cleaning',
    'cleaned a air conditioning coil' : 'Coil Cleaning',
    'cleaned a air conditioning coils' : 'Coil Cleaning',
    'cleaning of air conditioning coil' : 'Coil Cleaning',
    'cleaning of air conditioning coils' : 'Coil Cleaning',
    'air conditioner coil cleaning' : 'Coil Cleaning',
    'cleaned air conditioner coil' : 'Coil Cleaning',
    'cleaned air conditioner coils' : 'Coil Cleaning',
    'cleaned a air conditioner coil' : 'Coil Cleaning',
    'cleaned a air conditioner coils' : 'Coil Cleaning',
    'cleaning of air conditioner coil' : 'Coil Cleaning',
    'cleaning of air conditioner coils' : 'Coil Cleaning',

    'filter cleaning' : 'Filter Cleaning',
    'air conditioner filter cleaning' : 'Filter Cleaning',
    'cleaning filter' : 'Filter Cleaning',
    'cleaning filters' : 'Filter Cleaning',
    'cleaned filter' : 'Filter Cleaning',
    'cleaned filters' : 'Filter Cleaning',
    'cleaned air conditioner filter' : 'Filter Cleaning',
    'cleaned air conditioner filters' : 'Filter Cleaning',
    'cleaned a air conditioner filter' : 'Filter Cleaning',
    'cleaning of air conditioner filter' : 'Filter Cleaning',

#Sofa Maintenance
    'cushion replacement' : 'Cushion Replacement',
    'cushion replacements' : 'Cushion Replacement',
    'replacing cushion' : 'Cushion Replacement',
    'replacing cushions' : 'Cushion Replacement',
    'replacing of cushion' : 'Cushion Replacement',
    'replacing of cushions' : 'Cushion Replacement',
    'replacing of furniture cushion' : 'Cushion Replacement',
    'replacing of furniture cushions' : 'Cushion Replacement',
    
    'cushion repair' : 'Cushion Repair',
    'cushion repairs' : 'Cushion Repair',
    'repairing cushion' : 'Cushion Repair',
    'repairing cushions' : 'Cushion Repair',
    'repairing of cushion' : 'Cushion Repair',
    'repairing of cushions' : 'Cushion Repair',
    'repaired a cushion' : 'Cushion Repair',
    'repaired a cushions' : 'Cushion Repair',
    'repaired cushions' : 'Cushion Repair',

    'spring replacement' : 'Spring Replacement',
    'spring replacements' : 'Spring Replacement',
    'sofa spring replacement' : 'Spring Replacement',
    'sofa spring replacements' : 'Spring Replacement',
    'replacing spring' : 'Spring Replacement',
    'replacing springs' : 'Spring Replacement',
    'replacing sofa spring' : 'Spring Replacement',
    'replacing sofa springs' : 'Spring Replacement',
    'replacing of spring' : 'Spring Replacement',
    'replacing of springs' : 'Spring Replacement',
    'replacing of sofa spring' : 'Spring Replacement',
    'replacing of sofa springs' : 'Spring Replacement',
    'replaced a spring' : 'Spring Replacement',
    'replaced a springs' : 'Spring Replacement',
    'replaced a sofa spring' : 'Spring Replacement',
    'replaced a sofa springs' : 'Spring Replacement',
    'replaced spring' : 'Spring Replacement',
    'replaced springs' : 'Spring Replacement',
    'replaced sofa spring' : 'Spring Replacement',
    'replaced sofa springs' : 'Spring Replacement',

    'frame reinforcement' : 'Frame Reinforcement',
    'frame reinforcements' : 'Frame Reinforcement',
    'reinforcing frame' : 'Frame Reinforcement',
    'reinforcing frames' : 'Frame Reinforcement',
    'reinforcing of frame' : 'Frame Reinforcement',
    'reinforcing of frames' : 'Frame Reinforcement',
    'reinforced a frame' : 'Frame Reinforcement',
    'reinforced a frames' : 'Frame Reinforcement',
    'reinforced frame' : 'Frame Reinforcement',
    'reinforced frames' : 'Frame Reinforcement',

    'upholstery cleaning' : 'Upholstery Cleaning',
    'upholsteries cleaning' : 'Upholstery Cleaning',
    'cleaning upholstery' : 'Upholstery Cleaning',
    'cleaning upholsteries' : 'Upholstery Cleaning',
    'cleaning of upholstery' : 'Upholstery Cleaning',
    'cleaning of upholsteries' : 'Upholstery Cleaning',
    'cleaned a upholstery' : 'Upholstery Cleaning',
    'cleaned a upholsteries' : 'Upholstery Cleaning',
    'cleaned upholstery' : 'Upholstery Cleaning',
    'cleaned upholsteries' : 'Upholstery Cleaning',

    'spring replacement' : 'Spring Replacement',
    'spring replacements' : 'Spring Replacement',
    'sofa spring replacement' : 'Spring Replacement',
    'sofa spring replacements' : 'Spring Replacement',
    'replacing spring' : 'Spring Replacement',
    'replacing springs' : 'Spring Replacement',
    'replacing sofa spring' : 'Spring Replacement',
    'replacing sofa springs' : 'Spring Replacement',
    'replacing of spring' : 'Spring Replacement',
    'replacing of springs' : 'Spring Replacement',
    'replacing of sofa spring' : 'Spring Replacement',
    'replacing of sofa springs' : 'Spring Replacement',
    'replaced a spring' : 'Spring Replacement',
    'replaced a springs' : 'Spring Replacement',
    'replaced a sofa spring' : 'Spring Replacement',
    'replaced a sofa springs' : 'Spring Replacement',
    'replaced spring' : 'Spring Replacement',
    'replaced springs' : 'Spring Replacement',
    'replaced sofa spring' : 'Spring Replacement',
    'replaced sofa springs' : 'Spring Replacement',
   
# Bed Maintenance
    'frame tightening' : 'Frame Tightening',
    'bed frame tightening' : 'Frame Tightening',
    'tightening frame' : 'Frame Tightening',
    'tightening frames' : 'Frame Tightening',
    'tightening bed frame' : 'Frame Tightening',
    'tightening bed frames' : 'Frame Tightening',
    'tightening of frame' : 'Frame Tightening',
    'tightening of frames' : 'Frame Tightening',
    'tightening of bed frame' : 'Frame Tightening',
    'tightening of bed frames' : 'Frame Tightening',
    'tightened a frame' : 'Frame Tightening',
    'tightened a frames' : 'Frame Tightening',
    'tightened a bed frame' : 'Frame Tightening',
    'tightened a bed frames' : 'Frame Tightening',
    'tightened frame' : 'Frame Tightening',
    'tightened frames' : 'Frame Tightening',
    'tightened bed frame' : 'Frame Tightening',
    'tightened bed frames' : 'Frame Tightening',

    'frame tightening' : 'Frame Tightening',
    'bed frame tightening' : 'Frame Tightening',
    'tightening frame' : 'Frame Tightening',
    'tightening frames' : 'Frame Tightening',
    'tightening bed frame' : 'Frame Tightening',
    'tightening bed frames' : 'Frame Tightening',
    'tightening of frame' : 'Frame Tightening',
    'tightening of frames' : 'Frame Tightening',
    'tightening of bed frame' : 'Frame Tightening',
    'tightening of bed frames' : 'Frame Tightening',
    'tightened a frame' : 'Frame Tightening',
    'tightened a frames' : 'Frame Tightening',
    'tightened a bed frame' : 'Frame Tightening',
    'tightened a bed frames' : 'Frame Tightening',
    'tightened frame' : 'Frame Tightening',
    'tightened frames' : 'Frame Tightening',
    'tightened bed frame' : 'Frame Tightening',
    'tightened bed frames' : 'Frame Tightening',

    'slat replacement' : 'Slat Replacement',
    'slat replacements' : 'Slat Replacement',
    'bed slat replacement' : 'Slat Replacement',
    'bed slat replacements' : 'Slat Replacement',
    'replacing slat' : 'Slat Replacement',
    'replacing slats' : 'Slat Replacement',
    'replacing bed slat' : 'Slat Replacement',
    'replacing bed slats' : 'Slat Replacement',
    'replacing of slat' : 'Slat Replacement',
    'replacing of slats' : 'Slat Replacement',
    'replacing of bed slat' : 'Slat Replacement',
    'replacing of bed slats' : 'Slat Replacement',
    'replaced a slat' : 'Slat Replacement',
    'replaced a slats' : 'Slat Replacement',
    'replaced a bed slat' : 'Slat Replacement',
    'replaced a bed slats' : 'Slat Replacement',
    'replaced slat' : 'Slat Replacement',
    'replaced slats' : 'Slat Replacement',
    'replaced bed slat' : 'Slat Replacement',
    'replaced bed slats' : 'Slat Replacement',

    'mattress rotation' : 'Mattress Rotation',
    'mattress rotations' : 'Mattress Rotation',
    'bed mattress rotation' : 'Mattress Rotation',
    'bed mattress rotations' : 'Mattress Rotation',
    'rotation mattress' : 'Mattress Rotation',
    'rotation mattresses' : 'Mattress Rotation',
    'rotation bed mattress' : 'Mattress Rotation',
    'rotation bed mattresses' : 'Mattress Rotation',
    'rotation of mattress' : 'Mattress Rotation',
    'rotation of mattresses' : 'Mattress Rotation',
    'rotation of bed mattress' : 'Mattress Rotation',
    'rotation of bed mattresses' : 'Mattress Rotation',
    'rotated a mattress' : 'Mattress Rotation',
    'rotated a mattresses' : 'Mattress Rotation',
    'rotated a bed mattress' : 'Mattress Rotation',
    'rotated a bed mattresses' : 'Mattress Rotation',
    'rotated mattress' : 'Mattress Rotation',
    'rotated mattresses' : 'Mattress Rotation',
    'rotated bed mattress' : 'Mattress Rotation',
    'rotated bed mattresses' : 'Mattress Rotation',

    'headboard repair' : 'Headboard Repair',
    'headboard repairs' : 'Headboard Repair',
    'bed headboard repair' : 'Headboard Repair',
    'bed headboard repairs' : 'Headboard Repair',
    'repairing headboard' : 'Headboard Repair',
    'repairing headboards' : 'Headboard Repair',
    'repairing bed headboard' : 'Headboard Repair',
    'repairing bed headboards' : 'Headboard Repair',
    'repairing of headboard' : 'Headboard Repair',
    'repairing of headboards' : 'Headboard Repair',
    'repairing of bed headboard' : 'Headboard Repair',
    'repairing of bed headboards' : 'Headboard Repair',
    'repaired a headboard' : 'Headboard Repair',
    'repaired a headboards' : 'Headboard Repair',
    'repaired a bed headboard' : 'Headboard Repair',
    'repaired a bed headboards' : 'Headboard Repair',
    'repaired headboard' : 'Headboard Repair',
    'repaired headboards' : 'Headboard Repair',
    'repaired bed headboard' : 'Headboard Repair',
    'repaired bed headboards' : 'Headboard Repair',

    #Cabinet Maintenace
    'lock replacement' : 'Lock Replacement',
    'lock replacements' : 'Lock Replacement',
    'cabinet lock replacement' : 'Lock Replacement',
    'cabinet lock replacements' : 'Lock Replacement',
    'replacing lock' : 'Lock Replacement',
    'replacing locks' : 'Lock Replacement',
    'replacing cabinet lock' : 'Lock Replacement',
    'replacing cabinet locks' : 'Lock Replacement',
    'replacing of lock' : 'Lock Replacement',
    'replacing of locks' : 'Lock Replacement',
    'replacing of cabinet lock' : 'Lock Replacement',
    'replacing of cabinet locks' : 'Lock Replacement',
    'replaced a lock' : 'Lock Replacement',
    'replaced a locks' : 'Lock Replacement',
    'replaced a cabinet lock' : 'Lock Replacement',
    'replaced a cabinet locks' : 'Lock Replacement',
    'replaced lock' : 'Lock Replacement',
    'replaced locks' : 'Lock Replacement',
    'replaced cabinet lock' : 'Lock Replacement',
    'replaced cabinet locks' : 'Lock Replacement',

    'handle replacement' : 'Handle Replacement',
    'handle replacements' : 'Handle Replacement',
    'cabinet handle replacement' : 'Handle Replacement',
    'cabinet handle replacements' : 'Handle Replacement',
    'replacing handle' : 'Handle Replacement',
    'replacing handles' : 'Handle Replacement',
    'replacing cabinet handle' : 'Handle Replacement',
    'replacing cabinet handles' : 'Handle Replacement',
    'replacing of handle' : 'Handle Replacement',
    'replacing of handles' : 'Handle Replacement',
    'replacing of cabinet handle' : 'Handle Replacement',
    'replacing of cabinet handles' : 'Handle Replacement',
    'replaced a handle' : 'Handle Replacement',
    'replaced a handles' : 'Handle Replacement',
    'replaced a cabinet handle' : 'Handle Replacement',
    'replaced a cabinet handles' : 'Handle Replacement',
    'replaced handle' : 'Handle Replacement',
    'replaced handles' : 'Handle Replacement',
    'replaced cabinet handle' : 'Handle Replacement',
    'replaced cabinet handles' : 'Handle Replacement',

    'cabinet refacing' : 'Cabinet Refacing',
    'cabinet refacings' : 'Cabinet Refacing',
    'refacing cabinet' : 'Cabinet Refacing',
    'refacing cabinets' : 'Cabinet Refacing',
    'refacing of cabinet' : 'Cabinet Refacing',
    'refacing of cabinets' : 'Cabinet Refacing',
    'refaced a cabinet' : 'Cabinet Refacing',
    'refaced a cabinets' : 'Cabinet Refacing',
    'refaced cabinet' : 'Cabinet Refacing',
    'refaced cabinets' : 'Cabinet Refacing',

    'cabinet repair' : 'Cabinet Repair',
    'cabinet repairs' : 'Cabinet Repair',
    'repairing cabinet' : 'Cabinet Repair',
    'repairing cabinets' : 'Cabinet Repair',
    'repairing of cabinet' : 'Cabinet Repair',
    'repairing of cabinets' : 'Cabinet Repair',
    'repaired a cabinet' : 'Cabinet Repair',
    'repaired a cabinets' : 'Cabinet Repair',
    'repaired cabinet' : 'Cabinet Repair',
    'repaired cabinets' : 'Cabinet Repair',

    'hinge replacement' : 'Hinge Replacement',
    'hinge replacements' : 'Hinge Replacement',
    'cabinet hinge replacement' : 'Hinge Replacement',
    'cabinet hinge replacements' : 'Hinge Replacement',
    'replacing hinge' : 'Hinge Replacement',
    'replacing hinges' : 'Hinge Replacement',
    'replacing cabinet hinge' : 'Hinge Replacement',
    'replacing cabinet hinges' : 'Hinge Replacement',
    'replacing of hinge' : 'Hinge Replacement',
    'replacing of hinges' : 'Hinge Replacement',
    'replacing of cabinet hinge' : 'Hinge Replacement',
    'replacing of cabinet hinges' : 'Hinge Replacement',
    'replaced a hinge' : 'Hinge Replacement',
    'replaced a hinges' : 'Hinge Replacement',
    'replaced a cabinet hinge' : 'Hinge Replacement',
    'replaced a cabinet hinges' : 'Hinge Replacement',
    'replaced hinge' : 'Hinge Replacement',
    'replaced hinges' : 'Hinge Replacement',
    'replaced cabinet hinge' : 'Hinge Replacement',
    'replaced cabinet hinges' : 'Hinge Replacement',

#Door Maintenance
    'door alignment' : 'Door Alignment',
    'door alignments' : 'Door Alignment',
    'aligning door' : 'Door Alignment',
    'aligning doors' : 'Door Alignment',
    'aligning of door' : 'Door Alignment',
    'aligning of doors' : 'Door Alignment',
    'aligned a door' : 'Door Alignment',
    'aligned a doors' : 'Door Alignment',
    'aligned door' : 'Door Alignment',
    'aligned doors' : 'Door Alignment',

    'door repair' : 'Door Repair',
    'door repairs' : 'Door Repair',
    'repairing door' : 'Door Repair',
    'repairing doors' : 'Door Repair',
    'repairing of door' : 'Door Repair',
    'repairing of doors' : 'Door Repair',
    'repaired a door' : 'Door Repair',
    'repaired a doors' : 'Door Repair',
    'repaired door' : 'Door Repair',
    'repaired doors' : 'Door Repair',

    'weather stripping installation' : 'Weather Stripping Installation',
    'weather stripping installations' : 'Weather Stripping Installation',
    'installing weather stripping' : 'Weather Stripping Installation',
    'installing weather strippings' : 'Weather Stripping Installation',
    'installing of weather stripping' : 'Weather Stripping Installation',
    'installing of weather strippings' : 'Weather Stripping Installation',
    'installed a weather stripping' : 'Weather Stripping Installation',
    'installed a weather strippings' : 'Weather Stripping Installation',
    'installed weather stripping' : 'Weather Stripping Installation',
    'installed weather strippings' : 'Weather Stripping Installation',

    'roller repair' : 'Roller Repair',
    'roller repairs' : 'Roller Repair',
    'roller track repair' : 'Roller Repair',
    'roller track repairs' : 'Roller Repair',
    'repairing roller' : 'Roller Repair',
    'repairing rollers' : 'Roller Repair',
    'repairing roller track' : 'Roller Repair',
    'repairing roller tracks' : 'Roller Repair',
    'repairing of roller' : 'Roller Repair',
    'repairing of rollers' : 'Roller Repair',
    'repairing of roller track' : 'Roller Repair',
    'repairing of roller tracks' : 'Roller Repair',
    'repaired a roller' : 'Roller Repair',
    'repaired a rollers' : 'Roller Repair',
    'repaired a roller track' : 'Roller Repair',
    'repaired a roller tracks' : 'Roller Repair',
    'repaired roller' : 'Roller Repair',
    'repaired rollers' : 'Roller Repair',
    'repaired roller track' : 'Roller Repair',
    'repaired roller tracks' : 'Roller Repair',

    'scratch repair' : 'Scratch Repair',
    'scratch repairs' : 'Scratch Repair',
    'repairing scratch' : 'Scratch Repair',
    'repairing scratches' : 'Scratch Repair',
    'repairing of scratch' : 'Scratch Repair',
    'repairing of scratches' : 'Scratch Repair',
    'repaired a scratch' : 'Scratch Repair',
    'repaired a scratches' : 'Scratch Repair',
    'repaired scratch' : 'Scratch Repair',
    'repaired scratches' : 'Scratch Repair',

    'dent repair' : 'Dent Repair',
    'dent repairs' : 'Dent Repair',
    'repairing dent' : 'Dent Repair',
    'repairing dents' : 'Dent Repair',
    'repairing of dent' : 'Dent Repair',
    'repairing of dents' : 'Dent Repair',
    'repaired a dent' : 'Dent Repair',
    'repaired a dents' : 'Dent Repair',
    'repaired dent' : 'Dent Repair',
    'repaired dents' : 'Dent Repair',

    'automatic door mechanism' : 'Automatic Door Mechanism',
    'automatic door mechanisms' : 'Automatic Door Mechanism',
    'installing automatic door mechanism' : 'Automatic Door Mechanism',
    'installing automatic door mechanisms' : 'Automatic Door Mechanism',
    'installing of automatic door mechanism' : 'Automatic Door Mechanism',
    'installing of automatic door mechanisms' : 'Automatic Door Mechanism',
    'installed a automatic door mechanism' : 'Automatic Door Mechanism',
    'installed a automatic door mechanisms' : 'Automatic Door Mechanism',
    'installed automatic door mechanism' : 'Automatic Door Mechanism',
    'installed automatic door mechanisms' : 'Automatic Door Mechanism',

    'hinge adjustment' : 'Hinge Adjustment',
    'hinge adjustments' : 'Hinge Adjustment',
    'adjusting hinge' : 'Hinge Adjustment',
    'adjusting hinges' : 'Hinge Adjustment',
    'adjusting of hinge' : 'Hinge Adjustment',
    'adjusting of hinges' : 'Hinge Adjustment',
    'adjusted a hinge' : 'Hinge Adjustment',
    'adjusted a hinges' : 'Hinge Adjustment',
    'adjusted hinge' : 'Hinge Adjustment',
    'adjusted hinges' : 'Hinge Adjustment',

#General Cleaning
    'sweeping floor' : 'Sweeping Floor',
    'sweeping floors' : 'Sweeping Floor',
    'sweeping of floor' : 'Sweeping Floor',
    'sweeping of floors' : 'Sweeping Floor',
    'swept a floor' : 'Sweeping Floor',
    'swept a floors' : 'Sweeping Floor',
    'swept floor' : 'Sweeping Floor',
    'swept floors' : 'Sweeping Floor',
    'floor sweeping' : 'Sweeping Floor',
    'floor sweepings' : 'Sweeping Floor',

    'mopping floor' : 'Mopping Floor',
    'mopping floors' : 'Mopping Floor',
    'mopping of floors' : 'Mopping Floor',
    'mopped a floor' : 'Mopping Floor',
    'mopped a floors' : 'Mopping Floor',
    'mopped floor' : 'Mopping Floor',
    'mopped floors' : 'Mopping Floor',
    'floor mopping' : 'Mopping Floor',
    'floor moppings' : 'Mopping Floor',

    'surface wiping' : 'Surface Wiping',
    'surface wipings' : 'Surface Wiping',
    'wiping surface' : 'Surface Wiping',
    'wiping surfaces' : 'Surface Wiping',
    'wiping of surface' : 'Surface Wiping',
    'wiping of surfaces' : 'Surface Wiping',
    'wiped a surface' : 'Surface Wiping',
    'wiped a surfaces' : 'Surface Wiping',
    'wiped surface' : 'Surface Wiping',
    'wiped surfaces' : 'Surface Wiping',

    'vacuuming carpet' : 'Vacuuming Carpet',
    'vacuuming carpets' : 'Vacuuming Carpet',
    'vacuuming of carpet' : 'Vacuuming Carpet',
    'vacuuming of carpets' : 'Vacuuming Carpet',
    'vacuumed a carpet' : 'Vacuuming Carpet',
    'vacuumed a carpets' : 'Vacuuming Carpet',
    'vacuumed carpet' : 'Vacuuming Carpet',
    'vacuumed carpets' : 'Vacuuming Carpet',
    'carpet vacuuming' : 'Vacuuming Carpet',
    'carpet vacuumings' : 'Vacuuming Carpet',

    'organizing' : 'Organizing',
    'organizing of' : 'Organizing',
    'organized a' : 'Organizing',
    'organized' : 'Organizing',

    'decluttering' : 'Decluttering',
    'decluttering of' : 'Decluttering',
    'decluttered a' : 'Decluttering',
    'decluttered' : 'Decluttering',

#Deep Cleaning
    'tile scrubbing' : 'Tile Scrubbing',
    'tile scrubbings' : 'Tile Scrubbing',
    'scrubbing tile' : 'Tile Scrubbing',
    'scrubbing tiles' : 'Tile Scrubbing',
    'scrubbing of tile' : 'Tile Scrubbing',
    'scrubbing of tiles' : 'Tile Scrubbing',
    'scrubbed a tile' : 'Tile Scrubbing',
    'scrubbed a tiles' : 'Tile Scrubbing',
    'scrubbed tile' : 'Tile Scrubbing',
    'scrubbed tiles' : 'Tile Scrubbing',

    'team cleaning' : 'Steam Cleaning',
    'cleaning with steam' : 'Steam Cleaning',
    'cleaning by steam' : 'Steam Cleaning',
    'steam cleaned a' : 'Steam Cleaning',
    'steam cleaned' : 'Steam Cleaning',

    'stain removal' : 'Stain Removal',
    'stain removals' : 'Stain Removal',
    'removing stain' : 'Stain Removal',
    'removing stains' : 'Stain Removal',
    'removing of stain' : 'Stain Removal',
    'removing of stains' : 'Stain Removal',
    'removed a stain' : 'Stain Removal',
    'removed a stains' : 'Stain Removal',
    'removed stain' : 'Stain Removal',
    'removed stains' : 'Stain Removal',

    'upholstery deep cleaning' : 'Upholstery Deep Cleaning',
    'upholstery deep cleanings' : 'Upholstery Deep Cleaning',
    'deep cleaning upholstery' : 'Upholstery Deep Cleaning',
    'deep cleaning upholsteries' : 'Upholstery Deep Cleaning',
    'deep cleaning of upholstery' : 'Upholstery Deep Cleaning',
    'deep cleaning of upholsteries' : 'Upholstery Deep Cleaning',
    'deep cleaned a upholstery' : 'Upholstery Deep Cleaning',
    'deep cleaned a upholsteries' : 'Upholstery Deep Cleaning',
    'deep cleaned upholstery' : 'Upholstery Deep Cleaning',
    'deep cleaned upholsteries' : 'Upholstery Deep Cleaning',

    'mattress sanitizing' : 'Mattress Sanitizing',
    'mattress sanitizings' : 'Mattress Sanitizing',
    'sanitizing mattress' : 'Mattress Sanitizing',
    'sanitizing mattresses' : 'Mattress Sanitizing',
    'sanitizing of mattress' : 'Mattress Sanitizing',
    'sanitizing of mattresses' : 'Mattress Sanitizing',
    'sanitized a mattress' : 'Mattress Sanitizing',
    'sanitized a mattresses' : 'Mattress Sanitizing',
    'sanitized mattress' : 'Mattress Sanitizing',
    'sanitized mattresses' : 'Mattress Sanitizing',

    'vacuuming carpet': 'Vacuuming Carpet',
    'vacuuming carpets': 'Vacuuming Carpet',
    'vacuuming of carpet': 'Vacuuming Carpet',
    'vacuuming of carpets': 'Vacuuming Carpet',
    'vacuumed a carpet': 'Vacuuming Carpet',
    'vacuumed a carpets': 'Vacuuming Carpet',
    'vacuumed carpet': 'Vacuuming Carpet',
    'vacuumed carpets': 'Vacuuming Carpet',
    'carpet vacuuming': 'Vacuuming Carpet',
    'carpet vacuumings': 'Vacuuming Carpet',

#Laundry 
    'clothes sorting': 'Clothes Sorting',
    'clothes sortings': 'Clothes Sorting',
    'sorting cloth': 'Clothes Sorting',
    'sorting clothes': 'Clothes Sorting',
    'sorting of clothes': 'Clothes Sorting',
    'sorted a cloth': 'Clothes Sorting',
    'sorted a clothes': 'Clothes Sorting',
    'sorted cloth': 'Clothes Sorting',
    'sorted clothes': 'Clothes Sorting',

    'hand washing': 'Hand Washing',
    'washing by hand': 'Hand Washing',
    'washing of clothes by hand': 'Hand Washing',
    'hand washed': 'Hand Washing',
    'hand washed a': 'Hand Washing',
    'hand washed clothes': 'Hand Washing',

    'hand washing delicates': 'Hand Washing Delicates',
    'hand washing delicate': 'Hand Washing Delicates',
    'washing delicates by hand': 'Hand Washing Delicates',
    'washing a delicate by hand': 'Hand Washing Delicates',
    'hand washed a delicate': 'Hand Washing Delicates',
    'hand washed delicates': 'Hand Washing Delicates',
    'hand washed delicate': 'Hand Washing Delicates',

    'ironing': 'Ironing',
    'ironing of cloth': 'Ironing',
    'ironing of clothes': 'Ironing',
    'ironed a cloth': 'Ironing',
    'ironed a clothes': 'Ironing',
    'ironed cloth': 'Ironing',
    'ironed clothes': 'Ironing',

    'stain removal': 'Stain Removal',
    'stain removals': 'Stain Removal',
    'removing stain': 'Stain Removal',
    'removing stains': 'Stain Removal',
    'removing of stain': 'Stain Removal',
    'removing of stains': 'Stain Removal',
    'removed a stain': 'Stain Removal',
    'removed a stains': 'Stain Removal',
    'removed stain': 'Stain Removal',
    'removed stains': 'Stain Removal'
}

for text in test_texts:
    doc = improved_nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    print(f'Text: {text}')
    print(f'Entities: {entities}')
    print()