train_data = [
    # ----------- Refrigerator Maintenance -----------

    # condenser coil cleaning
    ("Condenser coil cleaning improves refrigerator efficiency and cooling.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Cleaning condenser coil removes dust and enhances cooling performance.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Cleaning condenser coils ensures proper heat dissipation.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Cleaned condenser coil restored refrigerator cooling efficiency.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Cleaned condenser coils removed dust and improved refrigerator performance.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Cleaned refrigerator condenser coil ensured optimal cooling.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Cleaned refrigerator condenser coils maintained efficient heat exchange.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Cleaning of refrigerator condenser coil prevents frost buildup.", 
     {"entities": [(0, 36, "SKILL")]}),
    ("Cleaning of refrigerator condenser coils maintains optimal refrigerator performance.", 
     {"entities": [(0, 37, "SKILL")]}),

    # defrost system maintenance
    ("Defrost system maintenance prevents ice buildup and ensures proper cooling.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Maintenance of defrost system keeps the refrigerator operating efficiently.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Maintenance of defrost systems ensures uniform cooling throughout the fridge.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Maintaining defrost system prevents frost accumulation and motor strain.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Maintaining defrost systems ensures consistent refrigerator performance.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Maintaining of defrost system avoids ice formation and enhances cooling.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Maintaining of defrost systems keeps the refrigerator frost-free and efficient.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Maintained defrost system restored proper cooling and reduced ice buildup.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Maintained defrost systems prevented frost accumulation and improved efficiency.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Maintained a defrost system ensured even cooling and optimal refrigerator performance.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Maintained a defrost systems kept the fridge frost-free and running smoothly.", 
     {"entities": [(0, 27, "SKILL")]}),

    # thermostat control checking
    ("Thermostat control checking ensures the refrigerator maintains the correct temperature.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Checking thermostat control prevents temperature fluctuations and keeps food fresh.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Checking thermostat controls ensures consistent cooling throughout the refrigerator.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Checking of thermostat control maintains proper fridge temperature and efficiency.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Checking of thermostat controls prevents cooling errors and improves refrigerator performance.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Checked a thermostat control restored proper temperature and efficient cooling.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Checked a thermostat controls ensured uniform temperature throughout the refrigerator.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Checked thermostat control fixed temperature inconsistencies effectively.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Checked thermostat controls maintained optimal refrigerator cooling performance.", 
     {"entities": [(0, 25, "SKILL")]}),

    # ice maker repair
    ("Ice maker repair ensures proper ice production and prevents leakage.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Ice maker repairs restore the functionality of the refrigerator's ice system.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing ice maker fixes malfunctions and improves ice quality.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing ice makers ensures consistent ice production and prevents clogs.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing of ice maker prevents freezing issues and maintains performance.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repairing of ice makers restores proper ice maker operation and efficiency.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repaired a ice maker fixed ice production and eliminated leaks.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repaired a ice makers restored ice production consistency.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired ice maker improved ice quality and refrigerator performance.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired ice makers maintained proper ice output and prevented jams.", 
     {"entities": [(0, 18, "SKILL")]}),
]
