train_data = [
    # ----------- Shower Maintenance -----------
    # clog removal
    ("Clog removal is necessary to maintain proper drainage.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Removal of clog is performed frequently in commercial kitchens.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removal of clogs helps prevent plumbing emergencies.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Removing clog requires proper tools and careful handling.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Removing clogs is often handled by professional plumbers.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Removing of clog was part of the routine maintenance.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Removing of clogs requires high-pressure equipment.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("The plumber removed a clog from the kitchen sink.", 
     {"entities": [(15, 28, "SKILL")]}),
    ("He removed a clogs quickly to restore drainage.", 
     {"entities": [(3, 18, "SKILL")]}),
    ("Removed clog was maintained by the maintenance team.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("The team removed clogs in multiple apartments yesterday.", 
     {"entities": [(9, 21, "SKILL")]}),

    # showerhead repair
    ("Showerhead repair is necessary to fix leaks in bathrooms.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Showerhead repairs are frequently performed by plumbers.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing showerhead requires proper tools and skill.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repairing showerheads is part of routine bathroom maintenance.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repairing of showerhead was scheduled for this morning.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repairing of showerheads helps prevent water leaks.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("The plumber repaired a showerhead in the master bathroom.", 
     {"entities": [(15, 31, "SKILL")]}),
    ("He repaired showerheads quickly to restore water flow.", 
     {"entities": [(3, 19, "SKILL")]}),

    # valve replacement
    ("Valve replacement is needed to ensure proper water control.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Valve replacements are commonly performed during plumbing upgrades.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing valve requires proper tools and attention to detail.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing valves is part of routine bathroom maintenance.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing of valve was scheduled for the morning.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replacing of valves ensures smooth water operation.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Replacement of valve is sometimes necessary after leaks.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replacement of valves helps maintain plumbing systems.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("The plumber replaced a valve in the shower system.", 
     {"entities": [(15, 28, "SKILL")]}),
    ("He replaced valves quickly to restore proper flow.", 
     {"entities": [(3, 16, "SKILL")]}),

    # shower pipe repair
    ("Shower pipe repair is necessary to prevent water leaks.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Shower pipe repairs are regularly performed in bathrooms.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repairing shower pipe requires high-quality tools.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repairing shower pipes is part of standard maintenance.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repairing of shower pipe was scheduled this morning.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Repairing of shower pipes prevents water damage.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("The plumber repaired a shower pipe in the master bathroom.", 
     {"entities": [(15, 31, "SKILL")]}),
    ("He repaired shower pipes quickly to restore water flow.", 
     {"entities": [(3, 19, "SKILL")]}),
]
