train_data = [
    # ----------- Sofa Maintenance -----------
    # cushion replacement
    ("Cushion replacement restores comfort and maintains sofa appearance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Cushion replacements ensure proper support and extend sofa lifespan.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replacing cushion improves seating comfort and prevents sagging.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing cushions restores sofa shape and enhances overall support.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing of cushion prevents wear and maintains seating comfort.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Replacing of cushions ensures proper cushion alignment and sofa durability.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replacing of furniture cushion restores original comfort and support.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Replacing of furniture cushions improves seating experience and maintains sofa quality.", 
     {"entities": [(0, 30, "SKILL")]}),

    # cushion repair
    ("Cushion repair restores torn fabric and maintains sofa comfort.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Cushion repairs fix worn-out cushions and ensure proper seating support.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Repairing cushion strengthens damaged areas and improves comfort.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing cushions restores proper shape and prolongs sofa life.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing of cushion fixes internal stuffing and enhances comfort.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repairing of cushions strengthens fabric and maintains sofa support.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repaired a cushion restored proper shape and improved seating comfort.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired a cushions fixed tears and strengthened support for the sofa.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repaired cushions restored cushioning and enhanced comfort for seating.", 
     {"entities": [(0, 16, "SKILL")]}),

    # frame reinforcement
    ("Frame reinforcement strengthens the sofa structure and ensures durability.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Frame reinforcements prevent sagging and maintain sofa integrity.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Reinforcing frame stabilizes the sofa and extends its lifespan.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Reinforcing frames ensures proper support and improves seating comfort.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Reinforcing of frame strengthens joints and enhances sofa durability.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Reinforcing of frames improves stability and maintains structural support.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Reinforced a frame restored sofa stability and ensured proper support.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Reinforced a frames strengthened the sofa and prevented sagging.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Reinforced frame enhanced sofa durability and improved seating comfort.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Reinforced frames stabilized the structure and extended sofa lifespan.", 
     {"entities": [(0, 18, "SKILL")]}),

    # upholstery cleaning
    ("Upholstery cleaning removes stains and maintains sofa appearance.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Upholsteries cleaning ensures fabric hygiene and prolongs sofa lifespan.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Cleaning upholstery restores fabric texture and improves sofa comfort.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Cleaning upholsteries removes dirt and ensures proper maintenance.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Cleaning of upholstery protects fabric and maintains sofa quality.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Cleaning of upholsteries removes embedded dust and improves seating comfort.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Cleaned a upholstery restored sofa appearance and removed stains effectively.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Cleaned a upholsteries ensured fabric cleanliness and improved comfort.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Cleaned upholstery eliminated dirt and maintained proper sofa hygiene.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Cleaned upholsteries removed stubborn stains and prolonged sofa lifespan.", 
     {"entities": [(0, 20, "SKILL")]}),
]
