train_data = [
    # ----------- Television Maintenance -----------
    # screen replacement
    ("Screen replacement is essential for restoring television display clarity.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Screen replacements prevent malfunction and improve viewing experience.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replacing screen fixes cracks and display issues effectively.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Replacing screens ensures optimal image quality and performance.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Replacing of screen is done to maintain television functionality.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing of screens prevents further damage to TV panels.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replaced a screen restored proper display and resolution.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replaced a screens improved television clarity and performance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced screen fixed the broken panel efficiently.", 
     {"entities": [(0, 14, "SKILL")]}),
    ("Replaced screens ensured better image quality for the TV.", 
     {"entities": [(0, 15, "SKILL")]}),
    ("Replacement of screen is necessary when cracks appear.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replacement of screens ensures consistent television performance.", 
     {"entities": [(0, 22, "SKILL")]}),

    # screen repair
    ("Screen repair restores the television display to optimal quality.", 
     {"entities": [(0, 12, "SKILL")]}),
    ("Screen repairing fixes broken pixels and damaged panels effectively.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repairing screen improves display performance and clarity.", 
     {"entities": [(0, 16, "SKILL")]}),
    ("Repairing screens ensures proper functioning of all display components.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repairing of screen is necessary when there are cracks or dead pixels.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing of screens prevents further damage and maintains image quality.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Repaired a screen restored proper display and resolution.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Repaired a screens improved television clarity and performance.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repaired screen fixed all display issues efficiently.", 
     {"entities": [(0, 13, "SKILL")]}),
    ("Repaired screens ensured proper image quality for the television.", 
     {"entities": [(0, 14, "SKILL")]}),

    # remote sensor repair
    ("Remote sensor repair ensures proper functioning of the TV control system.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Remote sensor repairs prevent connectivity issues with the television.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Remote sensor repairing restores accurate signal reception.", 
     {"entities": [(0, 24, "SKILL")]}),
    ("Repairing remote sensor ensures the TV responds to commands correctly.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repairing remote sensors prevents control issues and malfunction.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repairing of remote sensor restores proper communication with the device.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Repairing of remote sensors prevents lag in remote operation.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Repaired a remote sensor restored proper TV control.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repaired a remote sensors improved device response accuracy.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repaired remote sensor fixed all connectivity issues.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired remote sensors ensured proper operation of all controls.", 
     {"entities": [(0, 22, "SKILL")]}),

    # power supply board repair
    ("Power supply board repair is crucial for proper television operation.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Power supply board repairs prevent voltage fluctuations and device damage.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Power supply board repairing fixes electrical faults efficiently.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repairing power supply board ensures stable device performance.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Repairing power supply boards prevents TV malfunctions.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Repairing of power supply board restores full device functionality.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Repairing of power supply boards improves television reliability.", 
     {"entities": [(0, 33, "SKILL")]}),
    ("Repaired a power supply board fixed all voltage issues.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Repaired a power supply boards restored full device operation.", 
     {"entities": [(0, 30, "SKILL")]}),
    ("Repaired power supply board ensured proper television performance.", 
     {"entities": [(0, 26, "SKILL")]}),
    ("Repaired power supply boards prevented further device damage.", 
     {"entities": [(0, 27, "SKILL")]}),

    # control panel troubleshooting
    ("Control panel troubleshooting ensures proper operation of the device.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Troubleshooting control panel fixes all input and output issues.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Troubleshooting control panels prevents system errors and malfunctions.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Troubleshooting of control panel restores full functionality.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Troubleshooting of control panels improves device reliability.", 
     {"entities": [(0, 32, "SKILL")]}),
    ("Troubleshoot control panel prevents recurring errors efficiently.", 
     {"entities": [(0, 27, "SKILL")]}),
    ("Troubleshoot control panels ensures smooth operation of all functions.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Troubleshot control panel restored proper device performance.", 
     {"entities": [(0, 28, "SKILL")]}),
    ("Troubleshot control panels fixed recurring errors and malfunctions.", 
     {"entities": [(0, 29, "SKILL")]}),
    ("Troubleshot a control panel ensured correct input and output signals.", 
     {"entities": [(0, 31, "SKILL")]}),
    ("Troubleshot a control panels prevented future system failures.", 
     {"entities": [(0, 32, "SKILL")]}),

    # backlight replacement
    ("Backlight replacement restores screen brightness to optimal levels.", 
     {"entities": [(0, 20, "SKILL")]}),
    ("Backlight replacements prevent uneven lighting and screen dimming.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replacing backlight improves display illumination and clarity.", 
     {"entities": [(0, 17, "SKILL")]}),
    ("Replacing backlights ensures consistent screen brightness across the panel.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replacing of backlight is necessary when brightness fades.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Replacing of backlights maintains optimal screen performance.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Replaced a backlight restored proper display brightness.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Replaced a backlights fixed dim areas on the screen.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Replaced backlight improved display clarity and visibility.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Replaced backlights restored uniform illumination across the TV.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Replacement of backlight is essential for proper screen function.", 
     {"entities": [(0, 25, "SKILL")]}),
    ("Replacement of backlights prevents uneven lighting and flickering.", 
     {"entities": [(0, 26, "SKILL")]}),

    # backlight repair
    ("Backlight repair fixes dim or flickering screens effectively.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Backlight repairs restore proper brightness across the display.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing backlight ensures consistent illumination for the TV.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repairing backlights fixes uneven lighting on the screen.", 
     {"entities": [(0, 19, "SKILL")]}),
    ("Repairing of backlight prevents further dimming and flickering.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repairing of backlights maintains optimal display brightness.", 
     {"entities": [(0, 23, "SKILL")]}),
    ("Repaired a backlight fixed the dim areas on the screen.", 
     {"entities": [(0, 21, "SKILL")]}),
    ("Repaired a backlights restored proper illumination across the TV.", 
     {"entities": [(0, 22, "SKILL")]}),
    ("Repaired backlight improved display brightness and clarity.", 
     {"entities": [(0, 18, "SKILL")]}),
    ("Repaired backlights fixed flickering and dimming issues effectively.", 
     {"entities": [(0, 19, "SKILL")]}),
]
